"""
players.py — Player lists for UCL and PL tournaments.
Switch via active tournament setting.
Prices stored in cents (€5.5m = 5500000) for precision.
"""
import unicodedata
from typing import Optional


def _norm(s: str) -> str:
    """Normalize accents and special chars for matching."""
    # Handle chars that don't decompose well with NFKD first
    for ch, rep in [("\u0131","i"),("\u0130","i"),("\u011f","g"),("\u011e","g"),
                    ("\u015f","s"),("\u015e","s"),("\u00e7","c"),("\u00c7","c"),
                    ("\u00f6","o"),("\u00d6","o"),("\u00fc","u"),("\u00dc","u"),
                    ("\u00f1","n"),("\u00d1","n"),
                    ("\u00f8","o"),("\u00d8","o"),  # ø Ø -> o
                    ("\u00e6","ae"),("\u00c6","ae"), # æ Æ -> ae
                    ("\u00df","ss"),                  # ß -> ss
                    ]:
        s = s.replace(ch, rep)
    return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower().strip()

# ── UCL Players (Arsenal, PSG, Atletico Madrid, Bayern Munich) ────────────────

UCL_PLAYERS_RAW = [
    # Arsenal
    {"name": "Bukayo Saka",         "team": "Arsenal",  "pos": "MF", "price": 9500000},
    {"name": "Viktor Gyokeres",     "team": "Arsenal",  "pos": "FW", "price": 9000000},
    {"name": "Martin Odegaard",     "team": "Arsenal",  "pos": "MF", "price": 8500000},
    {"name": "Ademola Lookman",       "team": "Arsenal",  "pos": "FW", "price": 7000000},
    {"name": "Thomas Partey",          "team": "Arsenal",  "pos": "MF", "price": 6000000},
    {"name": "Gabriel Martinelli",  "team": "Arsenal",  "pos": "MF", "price": 7500000},
    {"name": "Kai Havertz",         "team": "Arsenal",  "pos": "FW", "price": 7500000},
    {"name": "Eberechi Eze",        "team": "Arsenal",  "pos": "MF", "price": 7500000},
    {"name": "Leandro Trossard",    "team": "Arsenal",  "pos": "MF", "price": 7000000},
    {"name": "Declan Rice",         "team": "Arsenal",  "pos": "MF", "price": 7000000},
    {"name": "Mikel Merino",        "team": "Arsenal",  "pos": "MF", "price": 6500000},
    {"name": "Noni Madueke",        "team": "Arsenal",  "pos": "MF", "price": 6500000},
    {"name": "William Saliba",      "team": "Arsenal",  "pos": "DEF","price": 6000000},
    {"name": "Martin Zubimendi",    "team": "Arsenal",  "pos": "MF", "price": 6000000},
    {"name": "Ethan Nwaneri",       "team": "Arsenal",  "pos": "MF", "price": 5500000},
    {"name": "Max Dowman",          "team": "Arsenal",  "pos": "MF", "price": 5500000},
    {"name": "Gabriel",             "team": "Arsenal",  "pos": "DEF","price": 5500000},
    {"name": "David Raya",          "team": "Arsenal",  "pos": "GK", "price": 5500000},
    {"name": "Ben White",           "team": "Arsenal",  "pos": "DEF","price": 5000000},
    {"name": "Christian Norgaard",  "team": "Arsenal",  "pos": "MF", "price": 5000000},
    {"name": "Piero Hincapie",      "team": "Arsenal",  "pos": "DEF","price": 5000000},
    {"name": "Jurrien Timber",      "team": "Arsenal",  "pos": "DEF","price": 5000000},
    {"name": "Kepa Arrizabalaga",   "team": "Arsenal",  "pos": "GK", "price": 4500000},
    {"name": "Cristhian Mosquera",  "team": "Arsenal",  "pos": "DEF","price": 4500000},
    {"name": "Riccardo Calafiori",  "team": "Arsenal",  "pos": "DEF","price": 4500000},
    {"name": "Myles Lewis-Skelly",  "team": "Arsenal",  "pos": "DEF","price": 4500000},
    {"name": "Tommy Setford",       "team": "Arsenal",  "pos": "GK", "price": 4000000},
    # PSG
    {"name": "Ousmane Dembele",     "team": "PSG",      "pos": "FW", "price": 10000000},
    {"name": "Desire Doue",         "team": "PSG",      "pos": "MF", "price": 8000000},
    {"name": "Khvicha Kvaratskhelia","team": "PSG",     "pos": "MF", "price": 8000000},
    {"name": "Bradley Barcola",     "team": "PSG",      "pos": "MF", "price": 7500000},
    {"name": "Goncalo Ramos",       "team": "PSG",      "pos": "FW", "price": 7000000},
    {"name": "Vitinha",             "team": "PSG",      "pos": "MF", "price": 7000000},
    {"name": "Fabian Ruiz",         "team": "PSG",      "pos": "MF", "price": 6500000},
    {"name": "Nuno Mendes",         "team": "PSG",      "pos": "DEF","price": 6000000},
    {"name": "Achraf Hakimi",       "team": "PSG",      "pos": "DEF","price": 6000000},
    {"name": "Joao Neves",          "team": "PSG",      "pos": "MF", "price": 6000000},
    {"name": "Kang-in Lee",         "team": "PSG",      "pos": "MF", "price": 6000000},
    {"name": "Warren Zaire-Emery",  "team": "PSG",      "pos": "MF", "price": 5500000},
    {"name": "Marquinhos",          "team": "PSG",      "pos": "DEF","price": 5000000},
    {"name": "Willian Pacho",       "team": "PSG",      "pos": "DEF","price": 5000000},
    {"name": "Ibrahim Mbaye",       "team": "PSG",      "pos": "MF", "price": 5000000},
    {"name": "Matvei Safonov",      "team": "PSG",      "pos": "GK", "price": 4500000},
    {"name": "Lucas Chevalier",     "team": "PSG",      "pos": "GK", "price": 4500000},
    {"name": "Senny Mayulu",        "team": "PSG",      "pos": "MF", "price": 4500000},
    {"name": "David Boly",          "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Lucas Hernandez",     "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Lucas Beraldo",       "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Illia Zabarnyi",      "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Martin James",        "team": "PSG",      "pos": "MF", "price": 4000000},
    {"name": "Noham Kamara",        "team": "PSG",      "pos": "DEF","price": 4000000},
    # Atletico Madrid
    {"name": "Julian Alvarez",      "team": "Atletico", "pos": "FW", "price": 9000000},
    {"name": "Antoine Griezmann",   "team": "Atletico", "pos": "FW", "price": 8500000},
    {"name": "Alexander Sorloth",   "team": "Atletico", "pos": "FW", "price": 7500000},
    {"name": "Marcos Llorente",     "team": "Atletico", "pos": "MF", "price": 6500000},
    {"name": "Giuliano Simeone",    "team": "Atletico", "pos": "MF", "price": 6000000},
    {"name": "Giacomo Raspadori",   "team": "Atletico", "pos": "FW", "price": 6000000},
    {"name": "Jan Oblak",           "team": "Atletico", "pos": "GK", "price": 6000000},
    {"name": "Koke",                "team": "Atletico", "pos": "MF", "price": 6000000},
    {"name": "Pablo Barrios",       "team": "Atletico", "pos": "MF", "price": 5500000},
    {"name": "Conor Gallagher",     "team": "Atletico", "pos": "MF", "price": 5500000},
    {"name": "Javier Galan",        "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Carlos Martin",       "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Nicolas Gonzalez",    "team": "Atletico", "pos": "MF", "price": 5000000},
    {"name": "Alex Baena",          "team": "Atletico", "pos": "MF", "price": 5000000},
    {"name": "Thiago Almada",       "team": "Atletico", "pos": "MF", "price": 5000000},
    {"name": "Jose Maria Gimenez",  "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Nahuel Molina",       "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Johnny Cardoso",      "team": "Atletico", "pos": "MF", "price": 4500000},
    {"name": "Juan Musso",          "team": "Atletico", "pos": "GK", "price": 4500000},
    {"name": "Robin Le Normand",    "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "Matteo Ruggeri",      "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "Clement Lenglet",     "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "David Hancko",        "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "Mario De Luis",       "team": "Atletico", "pos": "GK", "price": 4000000},
    {"name": "Marc Pubill",         "team": "Atletico", "pos": "DEF","price": 4000000},
    # Bayern Munich
    {"name": "Harry Kane",          "team": "Bayern",   "pos": "FW", "price": 10500000},
    {"name": "Jamal Musiala",       "team": "Bayern",   "pos": "MF", "price": 9000000},
    {"name": "Michael Olise",       "team": "Bayern",   "pos": "MF", "price": 8000000},
    {"name": "Luis Diaz",           "team": "Bayern",   "pos": "FW", "price": 7500000},
    {"name": "Joshua Kimmich",      "team": "Bayern",   "pos": "MF", "price": 6500000},
    {"name": "Serge Gnabry",        "team": "Bayern",   "pos": "MF", "price": 6500000},
    {"name": "Manuel Neuer",        "team": "Bayern",   "pos": "GK", "price": 6000000},
    {"name": "Leon Goretzka",       "team": "Bayern",   "pos": "MF", "price": 5500000},
    {"name": "Konrad Laimer",       "team": "Bayern",   "pos": "MF", "price": 5500000},
    {"name": "Tom Bischof",         "team": "Bayern",   "pos": "MF", "price": 5500000},
    {"name": "Jonathan Tah",        "team": "Bayern",   "pos": "DEF","price": 5500000},
    {"name": "Alphonso Davies",     "team": "Bayern",   "pos": "DEF","price": 5500000},
    {"name": "Dayot Upamecano",     "team": "Bayern",   "pos": "DEF","price": 5000000},
    {"name": "Aleksandar Pavlovic", "team": "Bayern",   "pos": "MF", "price": 5000000},
    {"name": "Raphael Guerreiro",   "team": "Bayern",   "pos": "DEF","price": 5000000},
    {"name": "Minjae Kim",          "team": "Bayern",   "pos": "DEF","price": 5000000},
    {"name": "Josip Stanisic",      "team": "Bayern",   "pos": "DEF","price": 4500000},
    {"name": "Jonas Urbig",         "team": "Bayern",   "pos": "GK", "price": 4500000},
    {"name": "Sacha Boey",          "team": "Bayern",   "pos": "DEF","price": 4000000},
    {"name": "Sven Ulreich",        "team": "Bayern",   "pos": "GK", "price": 4000000},
    {"name": "Hiroki Ito",          "team": "Bayern",   "pos": "DEF","price": 4000000},
]

# ── PL Players (all 20 teams) ──────────────────────────────────────────────────

PL_PLAYERS_RAW = [
    {"name": "Riccardo Calafiori", "team": "Arsenal", "pos": "DEF", "price": 5600000},
    {"name": "Kai Havertz", "team": "Arsenal", "pos": "FW", "price": 7300000},
    {"name": "Christian Norgaard", "team": "Arsenal", "pos": "MF", "price": 5100000},
    {"name": "Martin Odegaard", "team": "Arsenal", "pos": "MF", "price": 7800000},
    {"name": "Declan Rice", "team": "Arsenal", "pos": "MF", "price": 7200000},
    {"name": "Bukayo Saka", "team": "Arsenal", "pos": "MF", "price": 9800000},
    {"name": "William Saliba", "team": "Arsenal", "pos": "DEF", "price": 6100000},
    {"name": "Jurrien Timber", "team": "Arsenal", "pos": "DEF", "price": 6200000},
    {"name": "Leandro Trossard", "team": "Arsenal", "pos": "MF", "price": 6500000},
    {"name": "Kepa Arrizabalaga Revuelta", "team": "Arsenal", "pos": "GK", "price": 4500000},
    {"name": "Gabriel Dos Santos Magalhães", "team": "Arsenal", "pos": "FW", "price": 6000000},
    {"name": "Eberechi Oluchi Eze", "team": "Arsenal", "pos": "FW", "price": 7200000},
    {"name": "Gabriel Fernando De Jesus", "team": "Arsenal", "pos": "FW", "price": 6400000},
    {"name": "Viktor Einar Gyökeres", "team": "Arsenal", "pos": "FW", "price": 8800000},
    {"name": "Piero Martin Hincapie Reyna", "team": "Arsenal", "pos": "DEF", "price": 5000000},
    {"name": "Chukwunonso Azuka Tristan Madueke", "team": "Arsenal", "pos": "FW", "price": 6800000},
    {"name": "Mikel Merino Zazon", "team": "Arsenal", "pos": "MF", "price": 5500000},
    {"name": "David Raya Martin", "team": "Arsenal", "pos": "GK", "price": 4500000},
    {"name": "Gabriel Teodoro Martinelli Silva", "team": "Arsenal", "pos": "FW", "price": 6200000},
    {"name": "Benjamin White", "team": "Arsenal", "pos": "FW", "price": 5100000},
    {"name": "Martin Zubimendi Ibanez", "team": "Arsenal", "pos": "FW", "price": 6000000},
    {"name": "Marco Bizot", "team": "Aston Villa", "pos": "GK", "price": 4200000},
    {"name": "Lucas Digne", "team": "Aston Villa", "pos": "DEF", "price": 4500000},
    {"name": "John McGinn", "team": "Aston Villa", "pos": "MF", "price": 5300000},
    {"name": "Leon Patrick Bailey", "team": "Aston Villa", "pos": "FW", "price": 5500000},
    {"name": "Kevin Oghenetega Tamaraebi Bakumo-Abraham", "team": "Aston Villa", "pos": "FW", "price": 6000000},
    {"name": "Ross Barkley", "team": "Aston Villa", "pos": "MF", "price": 5500000},
    {"name": "Emiliano Buendia Stati", "team": "Aston Villa", "pos": "MF", "price": 5500000},
    {"name": "Matthew Stuart Cash", "team": "Aston Villa", "pos": "DEF", "price": 4700000},
    {"name": "Harvey Daniel James Elliott", "team": "Aston Villa", "pos": "FW", "price": 5100000},
    {"name": "Pau Francisco Torres", "team": "Aston Villa", "pos": "FW", "price": 4300000},
    {"name": "Andres Garcia Robledo", "team": "Aston Villa", "pos": "FW", "price": 6000000},
    {"name": "Boubacar Bernard Kamara", "team": "Aston Villa", "pos": "MF", "price": 5500000},
    {"name": "Ezri Ngoyo Konsa", "team": "Aston Villa", "pos": "DEF", "price": 4400000},
    {"name": "Ian Ethan Maatsen", "team": "Aston Villa", "pos": "DEF", "price": 4200000},
    {"name": "Damian Emiliano Martinez Romero", "team": "Aston Villa", "pos": "GK", "price": 5500000},
    {"name": "Tyrone Deon Mings", "team": "Aston Villa", "pos": "DEF", "price": 5000000},
    {"name": "Amadou Ba Z Mvom Onana", "team": "Aston Villa", "pos": "FW", "price": 4800000},
    {"name": "Victor Jorgen Nilsson Lindelof", "team": "Aston Villa", "pos": "DEF", "price": 5000000},
    {"name": "Morgan Elliot Rogers", "team": "Aston Villa", "pos": "FW", "price": 7400000},
    {"name": "Jadon Malik Sancho", "team": "Aston Villa", "pos": "MF", "price": 5800000},
    {"name": "Douglas Luiz Soares De Paulo", "team": "Aston Villa", "pos": "FW", "price": 6000000},
    {"name": "Youri Marion Tielemans", "team": "Aston Villa", "pos": "MF", "price": 5900000},
    {"name": "Oliver George Arthur Watkins", "team": "Aston Villa", "pos": "FW", "price": 8700000},
    {"name": "Ryan Christie", "team": "Bournemouth", "pos": "MF", "price": 4900000},
    {"name": "Enes Unal", "team": "Bournemouth", "pos": "FW", "price": 5400000},
    {"name": "Tyler Shaan Adams", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "Amine Adli", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "Owen Lucas Bevan", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "David Robert Brooks", "team": "Bournemouth", "pos": "MF", "price": 5500000},
    {"name": "Lewis John Cook", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "Francisco Evanilson De Lima Barbosa", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "William Jonathon Dennis", "team": "Bournemouth", "pos": "MF", "price": 5500000},
    {"name": "Bafode Diakite", "team": "Bournemouth", "pos": "DEF", "price": 5000000},
    {"name": "Fraser Gerard Forster", "team": "Bournemouth", "pos": "GK", "price": 4500000},
    {"name": "James Hill", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "Justin Dean Kluivert", "team": "Bournemouth", "pos": "DEF", "price": 6900000},
    {"name": "Christos Mandas", "team": "Bournemouth", "pos": "GK", "price": 4500000},
    {"name": "Djorde Petrovic", "team": "Bournemouth", "pos": "GK", "price": 4600000},
    {"name": "Dominic Wadi Sadi", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "Alex Jay Scott", "team": "Bournemouth", "pos": "FW", "price": 5100000},
    {"name": "Marcos Nicolas Senesi Baron", "team": "Bournemouth", "pos": "DEF", "price": 5000000},
    {"name": "Adam James Smith", "team": "Bournemouth", "pos": "FW", "price": 6000000},
    {"name": "Marcus Joseph Tavernier", "team": "Bournemouth", "pos": "MF", "price": 5400000},
    {"name": "Adrien Lillan Gaetan Truffert", "team": "Bournemouth", "pos": "FW", "price": 4700000},
    {"name": "Nathan Collins", "team": "Brentford", "pos": "DEF", "price": 4900000},
    {"name": "Vitaly Janelt", "team": "Brentford", "pos": "MF", "price": 4900000},
    {"name": "Kevin Schade", "team": "Brentford", "pos": "MF", "price": 7000000},
    {"name": "Sepp van den Berg", "team": "Brentford", "pos": "DEF", "price": 4600000},
    {"name": "Valentino Mayowa Adedokun", "team": "Brentford", "pos": "MF", "price": 5500000},
    {"name": "Kristoffer Vassbakk Ajer", "team": "Brentford", "pos": "DEF", "price": 5000000},
    {"name": "Ellery Ronald Balcombe", "team": "Brentford", "pos": "GK", "price": 4500000},
    {"name": "Matthew Aidan Cox", "team": "Brentford", "pos": "GK", "price": 4500000},
    {"name": "Mikkel Krogh Damsgaard", "team": "Brentford", "pos": "MF", "price": 5600000},
    {"name": "Pelenda Joshua Tunga Dasilva", "team": "Brentford", "pos": "DEF", "price": 5000000},
    {"name": "Fabio Leandro Freitas Gouveia De Carvalho", "team": "Brentford", "pos": "FW", "price": 4600000},
    {"name": "Jordan Brian Henderson", "team": "Brentford", "pos": "FW", "price": 5100000},
    {"name": "Rico Henry", "team": "Brentford", "pos": "FW", "price": 6000000},
    {"name": "Aaron Buchanan Hickey", "team": "Brentford", "pos": "DEF", "price": 5000000},
    {"name": "Mathias Jensen", "team": "Brentford", "pos": "FW", "price": 6000000},
    {"name": "Caoimhin Odhran Kelleher", "team": "Brentford", "pos": "FW", "price": 4800000},
    {"name": "Keane William Lewis-Potter", "team": "Brentford", "pos": "FW", "price": 6000000},
    {"name": "Igor Thiago Nascimento Rodrigues", "team": "Brentford", "pos": "MF", "price": 5500000},
    {"name": "Reiss Nelson", "team": "Brentford", "pos": "FW", "price": 6000000},
    {"name": "Dango Aboubacar Faissal Ouattara", "team": "Brentford", "pos": "FW", "price": 5900000},
    {"name": "Ethan Rupert Pinnock", "team": "Brentford", "pos": "DEF", "price": 5000000},
    {"name": "Hakon Rafn Valdimarsson", "team": "Brentford", "pos": "GK", "price": 4500000},
    {"name": "Kaoru Mitoma", "team": "Brighton", "pos": "MF", "price": 6100000},
    {"name": "Georginio Rutter", "team": "Brighton", "pos": "MF", "price": 5600000},
    {"name": "Jan Paul van Hecke", "team": "Brighton", "pos": "DEF", "price": 4600000},
    {"name": "Bart Verbruggen", "team": "Brighton", "pos": "GK", "price": 4500000},
    {"name": "Yasin Ayari", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Olivier Boscagli", "team": "Brighton", "pos": "DEF", "price": 5000000},
    {"name": "Maxim Peter De Cuyper", "team": "Brighton", "pos": "DEF", "price": 5000000},
    {"name": "Igor Julio Dos Santos De Paulo", "team": "Brighton", "pos": "FW", "price": 6000000},
    {"name": "Lewis Carl Dunk", "team": "Brighton", "pos": "DEF", "price": 4500000},
    {"name": "Diego Alexander Gomez Amarilla", "team": "Brighton", "pos": "FW", "price": 6000000},
    {"name": "Pascal Alexander Gross", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Ferdi Erenay Kadioglu", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Soloman Benjamin March", "team": "Brighton", "pos": "FW", "price": 6000000},
    {"name": "Thomas Peter Wayne McGill", "team": "Brighton", "pos": "GK", "price": 4500000},
    {"name": "James Phillips Milner", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Matthew Sean O'Riley", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Carl Andrew Rushworth", "team": "Brighton", "pos": "GK", "price": 4500000},
    {"name": "Jason Sean Steele", "team": "Brighton", "pos": "GK", "price": 4200000},
    {"name": "Joel Ivo Veltman", "team": "Brighton", "pos": "DEF", "price": 5000000},
    {"name": "Adam Harry Webster", "team": "Brighton", "pos": "DEF", "price": 5000000},
    {"name": "Daniel Welbeck", "team": "Brighton", "pos": "FW", "price": 6300000},
    {"name": "Mats Henrik Berne Wieffer", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Armando Broja", "team": "Burnley", "pos": "FW", "price": 5200000},
    {"name": "Maxime Esteve", "team": "Burnley", "pos": "DEF", "price": 3900000},
    {"name": "Zian Flemming", "team": "Burnley", "pos": "MF", "price": 5300000},
    {"name": "Mohamed Zeki Amdouni", "team": "Burnley", "pos": "FW", "price": 4800000},
    {"name": "Jaidon Anthony", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Ashley Barnes", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Martin Dubravka", "team": "Burnley", "pos": "GK", "price": 4500000},
    {"name": "Marcus Edwards", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Hjalmar Ekdal", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Lyle Brent Foster", "team": "Burnley", "pos": "FW", "price": 4900000},
    {"name": "Quilindschy Hartman", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Vaclav Hladky", "team": "Burnley", "pos": "GK", "price": 4500000},
    {"name": "Bashir Humphreys", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Jacob Bruun Larsen", "team": "Burnley", "pos": "FW", "price": 5900000},
    {"name": "Joshua Ishaele Jacob-Heron Laurent", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Hannibal Mejbri", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Florentina Ibrain Morris Luis", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Lucas Pires Silva", "team": "Burnley", "pos": "MF", "price": 6200000},
    {"name": "Connor Roberts", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Loum Tchaouna", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Mike Tresor Ndayishimiye", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Axel Tuanzebe", "team": "Burnley", "pos": "FW", "price": 6000000},
    {"name": "Kyle Andrew Walker", "team": "Burnley", "pos": "FW", "price": 4400000},
    {"name": "James Michael Edward Ward-Prowse", "team": "Burnley", "pos": "MF", "price": 5600000},
    {"name": "Joseph Adrian Worrall", "team": "Burnley", "pos": "MF", "price": 5500000},
    {"name": "Reece James", "team": "Chelsea", "pos": "DEF", "price": 5600000},
    {"name": "Filip Jorgensen", "team": "Chelsea", "pos": "GK", "price": 4300000},
    {"name": "Cole Palmer", "team": "Chelsea", "pos": "MF", "price": 10500000},
    {"name": "Abdul-Nasir Oluwatosin Adarabioyo", "team": "Chelsea", "pos": "DEF", "price": 5000000},
    {"name": "Benoit Ntambue Badiashile Mukinayi", "team": "Chelsea", "pos": "DEF", "price": 5000000},
    {"name": "Moises Isaac Caicedo Corozo", "team": "Chelsea", "pos": "MF", "price": 5500000},
    {"name": "Trevoh Tom Chalobah", "team": "Chelsea", "pos": "DEF", "price": 5000000},
    {"name": "Marc Cucurella Saseta", "team": "Chelsea", "pos": "DEF", "price": 5000000},
    {"name": "Liam Rory Delap", "team": "Chelsea", "pos": "FW", "price": 6200000},
    {"name": "Enzo Jeremias Fernandez", "team": "Chelsea", "pos": "FW", "price": 6500000},
    {"name": "Wesley Tidjan Fofana", "team": "Chelsea", "pos": "DEF", "price": 5000000},
    {"name": "Malo Arthur Gusto", "team": "Chelsea", "pos": "DEF", "price": 4900000},
    {"name": "Joao Pedro Junqueira De Jesus", "team": "Chelsea", "pos": "FW", "price": 6400000},
    {"name": "Pedro Lomba Neto", "team": "Chelsea", "pos": "FW", "price": 4500000},
    {"name": "Robert Lynch Sanchez", "team": "Chelsea", "pos": "FW", "price": 4800000},
    {"name": "Levi Lamar Samuels Colwill", "team": "Chelsea", "pos": "DEF", "price": 4700000},
    {"name": "Teddy Samuel Sharman-Lowe", "team": "Chelsea", "pos": "GK", "price": 4500000},
    {"name": "Jorgen Strand Larsen", "team": "Crystal Palace", "pos": "FW", "price": 5900000},
    {"name": "Jean-Philippe Mateta", "team": "Crystal Palace", "pos": "FW", "price": 7600000},
    {"name": "Tyrick Mitchell", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Ismaila Sarr", "team": "Crystal Palace", "pos": "MF", "price": 6300000},
    {"name": "Walter Daniel Benitez", "team": "Crystal Palace", "pos": "GK", "price": 4500000},
    {"name": "Nathaniel Edward Clyne", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Justin Devenny", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Cheick Oumar Doucoure", "team": "Crystal Palace", "pos": "MF", "price": 5500000},
    {"name": "Evann Ludovic Vidjannagni Guessand", "team": "Crystal Palace", "pos": "FW", "price": 6200000},
    {"name": "Dean Bradley Henderson", "team": "Crystal Palace", "pos": "FW", "price": 5100000},
    {"name": "William James Hughes", "team": "Crystal Palace", "pos": "MF", "price": 5500000},
    {"name": "Brennan Price Johnson", "team": "Crystal Palace", "pos": "MF", "price": 6500000},
    {"name": "Daichi Kamada", "team": "Crystal Palace", "pos": "MF", "price": 5500000},
    {"name": "Maxence Guy Lacroix", "team": "Crystal Palace", "pos": "DEF", "price": 5100000},
    {"name": "Jefferson Lerma", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Remi Luke Matthews", "team": "Crystal Palace", "pos": "FW", "price": 6000000},
    {"name": "Daniel Munoz Mejia", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Edward Keddar Nketiah", "team": "Crystal Palace", "pos": "MF", "price": 5400000},
    {"name": "Yeremy Jesus Pino Santos", "team": "Crystal Palace", "pos": "MF", "price": 5500000},
    {"name": "Chadi Riad Dnanou", "team": "Crystal Palace", "pos": "FW", "price": 6000000},
    {"name": "Christopher Jeffrey Richards", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Borna Sosa", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Vitalii Mykolenko", "team": "Everton", "pos": "DEF", "price": 4900000},
    {"name": "Carlos Jonas Alcaraz Duran", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "Thierno Mamadou Barry", "team": "Everton", "pos": "FW", "price": 5700000},
    {"name": "Jarrad Paul Branthwaite", "team": "Everton", "pos": "DEF", "price": 5300000},
    {"name": "Seamus Coleman", "team": "Everton", "pos": "DEF", "price": 5000000},
    {"name": "Kiernan Frank Dewsbury-Hall", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "James David Garner", "team": "Everton", "pos": "MF", "price": 5300000},
    {"name": "Norberto Bercique Gomes Betuncal", "team": "Everton", "pos": "FW", "price": 6000000},
    {"name": "Jack Peter Grealish", "team": "Everton", "pos": "FW", "price": 6300000},
    {"name": "Idrissa Gana Gueye", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "Timothy Emeka Iroegbunam", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "Michael Vincent Keane", "team": "Everton", "pos": "FW", "price": 6000000},
    {"name": "Thomas Lloyd King", "team": "Everton", "pos": "FW", "price": 6000000},
    {"name": "Dwight James Matthew McNeil", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "Iliman-Cheikh Baroy Ndiaye", "team": "Everton", "pos": "MF", "price": 6200000},
    {"name": "Jake Patrick O'Brien", "team": "Everton", "pos": "DEF", "price": 4900000},
    {"name": "Nathan Kenneth Patterson", "team": "Everton", "pos": "DEF", "price": 5000000},
    {"name": "Jordan Lee Pickford", "team": "Everton", "pos": "GK", "price": 5600000},
    {"name": "Merlin Rohl", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "James Alan Tarkowski", "team": "Everton", "pos": "FW", "price": 5700000},
    {"name": "Mark John Travers", "team": "Everton", "pos": "GK", "price": 4500000},
    {"name": "Reece Belfield Welch", "team": "Everton", "pos": "DEF", "price": 5000000},
    {"name": "Calvin Bassey", "team": "Fulham", "pos": "DEF", "price": 4400000},
    {"name": "Bernd Leno", "team": "Fulham", "pos": "GK", "price": 4900000},
    {"name": "Antonee Robinson", "team": "Fulham", "pos": "DEF", "price": 4900000},
    {"name": "Emile Smith Rowe", "team": "Fulham", "pos": "MF", "price": 5600000},
    {"name": "Harry Wilson", "team": "Fulham", "pos": "MF", "price": 6000000},
    {"name": "Joachim Christian Andersen", "team": "Fulham", "pos": "MF", "price": 4500000},
    {"name": "Sander Gard Bolin Berge", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Oscar Bobb", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Alexander Paul Borto", "team": "Fulham", "pos": "FW", "price": 6000000},
    {"name": "Thomas Cairney", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Samuel Chimerenka Chukwueze", "team": "Fulham", "pos": "FW", "price": 5300000},
    {"name": "Jorge Cuenca Barreno", "team": "Fulham", "pos": "DEF", "price": 5000000},
    {"name": "Issa Laye Lucas Jean Diop", "team": "Fulham", "pos": "FW", "price": 6000000},
    {"name": "Alexander Chuka Iwobi", "team": "Fulham", "pos": "MF", "price": 6300000},
    {"name": "Raul Alonso Jimenez Rodriguez", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Benjamin Pascal Lecomte", "team": "Fulham", "pos": "FW", "price": 6000000},
    {"name": "Sasa Lukic", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Rodrigo Muniz Carvalho", "team": "Fulham", "pos": "MF", "price": 4600000},
    {"name": "Harrison James Reed", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Kouassi Ryan Sessegnon", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Kenny Joelle Tete", "team": "Fulham", "pos": "MF", "price": 5500000},
    {"name": "Dominic Calvert-Lewin", "team": "Leeds", "pos": "FW", "price": 5700000},
    {"name": "Brenden Russell Aaronson", "team": "Leeds", "pos": "MF", "price": 5400000},
    {"name": "Ethan Kwame Colm Raymond Ampadu", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Jaka Bijol", "team": "Leeds", "pos": "DEF", "price": 5000000},
    {"name": "Jayden Ian Bogle", "team": "Leeds", "pos": "FW", "price": 4400000},
    {"name": "Sebastiaan Bornauw", "team": "Leeds", "pos": "DEF", "price": 5000000},
    {"name": "Samuel Mark Byram", "team": "Leeds", "pos": "DEF", "price": 5000000},
    {"name": "Alex Thomas Cairns", "team": "Leeds", "pos": "GK", "price": 4500000},
    {"name": "Karl Darlow", "team": "Leeds", "pos": "GK", "price": 4500000},
    {"name": "Degnand Wilfried Gnonto", "team": "Leeds", "pos": "MF", "price": 5100000},
    {"name": "Ilia Gruev", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Gabriel Johan Gudmundsson", "team": "Leeds", "pos": "DEF", "price": 5000000},
    {"name": "Daniel Owen James", "team": "Leeds", "pos": "FW", "price": 5600000},
    {"name": "James Michael Justin", "team": "Leeds", "pos": "DEF", "price": 5000000},
    {"name": "Sean David Longstaff", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Illan Stephane Meslier", "team": "Leeds", "pos": "GK", "price": 4100000},
    {"name": "Lukas Okechukwu Nmecha", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Noah Arinzechukwu Okafor", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Lucas Estella Perri", "team": "Leeds", "pos": "GK", "price": 4500000},
    {"name": "Joel Mohammed Ramzan Piroe", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Joseph Peter Rodon", "team": "Leeds", "pos": "DEF", "price": 5000000},
    {"name": "Anton Levi Stach", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Pascal Augustus Struijk", "team": "Leeds", "pos": "DEF", "price": 4300000},
    {"name": "Ao Tanaka", "team": "Leeds", "pos": "MF", "price": 5500000},
    {"name": "Conor Bradley", "team": "Liverpool", "pos": "DEF", "price": 4900000},
    {"name": "Jeremie Frimpong", "team": "Liverpool", "pos": "DEF", "price": 5700000},
    {"name": "Cody Gakpo", "team": "Liverpool", "pos": "MF", "price": 7300000},
    {"name": "Alexander Isak", "team": "Liverpool", "pos": "FW", "price": 10300000},
    {"name": "Ibrahima Konate", "team": "Liverpool", "pos": "DEF", "price": 5500000},
    {"name": "Alexis Mac Allister", "team": "Liverpool", "pos": "MF", "price": 6300000},
    {"name": "Giorgi Mamardashvili", "team": "Liverpool", "pos": "GK", "price": 4100000},
    {"name": "Andrew Robertson", "team": "Liverpool", "pos": "DEF", "price": 5700000},
    {"name": "Mohamed Salah", "team": "Liverpool", "pos": "MF", "price": 14000000},
    {"name": "Dominik Szoboszlai", "team": "Liverpool", "pos": "MF", "price": 7100000},
    {"name": "Virgil van Dijk", "team": "Liverpool", "pos": "DEF", "price": 6200000},
    {"name": "Owen Michael Beck", "team": "Liverpool", "pos": "FW", "price": 6000000},
    {"name": "Alisson Ramses Becker", "team": "Liverpool", "pos": "GK", "price": 5400000},
    {"name": "Federico Chiesa", "team": "Liverpool", "pos": "FW", "price": 6000000},
    {"name": "Harvey Davies", "team": "Liverpool", "pos": "GK", "price": 4500000},
    {"name": "Hugo Timothee Ekitike", "team": "Liverpool", "pos": "FW", "price": 9100000},
    {"name": "Wataru Endo", "team": "Liverpool", "pos": "MF", "price": 5500000},
    {"name": "Joseph David Gomez", "team": "Liverpool", "pos": "FW", "price": 6000000},
    {"name": "Ryan Jiro Gravenberch", "team": "Liverpool", "pos": "MF", "price": 5500000},
    {"name": "Curtis Jones", "team": "Liverpool", "pos": "FW", "price": 6000000},
    {"name": "Milos Kerkez", "team": "Liverpool", "pos": "MF", "price": 5500000},
    {"name": "Calvin Ramsay", "team": "Liverpool", "pos": "FW", "price": 6000000},
    {"name": "Rhys Williams", "team": "Liverpool", "pos": "FW", "price": 6000000},
    {"name": "Florian Richard Wirtz", "team": "Liverpool", "pos": "FW", "price": 8300000},
    {"name": "Frederick John Woodman", "team": "Liverpool", "pos": "GK", "price": 4500000},
    {"name": "Aaron Ramsdale", "team": "Newcastle", "pos": "GK", "price": 4500000},
    {"name": "Yoane Wissa", "team": "Newcastle", "pos": "FW", "price": 7300000},
    {"name": "Joelinton Cassio Apolinario De Lira", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Harvey Lewis Barnes", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Sven Adriaan Botman", "team": "Newcastle", "pos": "DEF", "price": 5000000},
    {"name": "Daniel Johnson Burn", "team": "Newcastle", "pos": "DEF", "price": 5000000},
    {"name": "Anthony David Junior Elanga", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Mark Joseph Gillespie", "team": "Newcastle", "pos": "GK", "price": 4500000},
    {"name": "Anthony Michael Gordon", "team": "Newcastle", "pos": "MF", "price": 5500000},
    {"name": "Bruno Guimaraes Rodriguez Moura", "team": "Newcastle", "pos": "MF", "price": 5500000},
    {"name": "Emil Henry Kristoffer Kraft", "team": "Newcastle", "pos": "DEF", "price": 5000000},
    {"name": "Valentino Livramento", "team": "Newcastle", "pos": "DEF", "price": 4900000},
    {"name": "Jacob Kai Murphy", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "William Idamudia Daugaard Osula", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Nicholas David Pope", "team": "Newcastle", "pos": "FW", "price": 5000000},
    {"name": "Jacob Matthew Decourcey Ramsey", "team": "Newcastle", "pos": "FW", "price": 5300000},
    {"name": "John Thomas Gordon Ruddy", "team": "Newcastle", "pos": "GK", "price": 4500000},
    {"name": "Fabian Lukas Schar", "team": "Newcastle", "pos": "DEF", "price": 5200000},
    {"name": "Malick Thiaw", "team": "Newcastle", "pos": "DEF", "price": 5000000},
    {"name": "Sandro Tonali", "team": "Newcastle", "pos": "MF", "price": 5500000},
    {"name": "Kieran John Trippier", "team": "Newcastle", "pos": "DEF", "price": 5000000},
    {"name": "Joseph George Willock", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Nick Woltemade", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Nikola Milenkovic", "team": "Nottm Forest", "pos": "DEF", "price": 4700000},
    {"name": "Temitayo Olufisayo Olaoluwa Aina", "team": "Nottm Forest", "pos": "MF", "price": 4900000},
    {"name": "Elliot Junior Anderson", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "Taiwo Micheal Awoniyi", "team": "Nottm Forest", "pos": "FW", "price": 5800000},
    {"name": "Dilane Ros-Anderson Bakwa", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "Murillo Santiago Costa Dos Santos", "team": "Nottm Forest", "pos": "DEF", "price": 5000000},
    {"name": "Nicolas Martin Dominguez", "team": "Nottm Forest", "pos": "MF", "price": 5500000},
    {"name": "Morgan Anthony Gibbs-White", "team": "Nottm Forest", "pos": "MF", "price": 6300000},
    {"name": "Omari Elijah Giraud-Hutchinson", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "Angus Fraser James Gunn", "team": "Nottm Forest", "pos": "GK", "price": 4500000},
    {"name": "Callum James Hudson-Odoi", "team": "Nottm Forest", "pos": "MF", "price": 5500000},
    {"name": "Lorenzo Lucca", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "Igor Jesus Maciel Da Cruz", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "John Victor Maciel Furtado", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "James John McAtee", "team": "Nottm Forest", "pos": "MF", "price": 5500000},
    {"name": "Dan Ndoye", "team": "Nottm Forest", "pos": "MF", "price": 5500000},
    {"name": "Luca Netz", "team": "Nottm Forest", "pos": "DEF", "price": 5000000},
    {"name": "Stefan Ortega Moreno", "team": "Nottm Forest", "pos": "GK", "price": 4500000},
    {"name": "Felipe Rodrigues Da Silva", "team": "Nottm Forest", "pos": "MF", "price": 6200000},
    {"name": "Ibrahim Sangare", "team": "Nottm Forest", "pos": "MF", "price": 5500000},
    {"name": "Nicolo Savona", "team": "Nottm Forest", "pos": "DEF", "price": 5000000},
    {"name": "Matz Willy Els Sels", "team": "Nottm Forest", "pos": "GK", "price": 5000000},
    {"name": "Neco Shay Williams", "team": "Nottm Forest", "pos": "FW", "price": 6000000},
    {"name": "Christopher Grant Wood", "team": "Nottm Forest", "pos": "FW", "price": 6700000},
    {"name": "Ryan James Yates", "team": "Nottm Forest", "pos": "MF", "price": 5500000},
    {"name": "Mohammed Kudus", "team": "Spurs", "pos": "MF", "price": 6700000},
    {"name": "Dejan Kulusevski", "team": "Spurs", "pos": "MF", "price": 6700000},
    {"name": "James Maddison", "team": "Spurs", "pos": "MF", "price": 6400000},
    {"name": "Micky van de Ven", "team": "Spurs", "pos": "DEF", "price": 5200000},
    {"name": "Guglielmo Vicario", "team": "Spurs", "pos": "GK", "price": 5000000},
    {"name": "Brandon Anthony Austin", "team": "Spurs", "pos": "GK", "price": 4500000},
    {"name": "Rodrigo Bentancur", "team": "Spurs", "pos": "MF", "price": 5500000},
    {"name": "Yves Bissouma", "team": "Spurs", "pos": "MF", "price": 5500000},
    {"name": "Matthew George Craig", "team": "Spurs", "pos": "FW", "price": 6000000},
    {"name": "Kevin Danso", "team": "Spurs", "pos": "DEF", "price": 5000000},
    {"name": "Benjamin Thomas Davies", "team": "Spurs", "pos": "GK", "price": 4500000},
    {"name": "Richarlison De Andrade", "team": "Spurs", "pos": "FW", "price": 6000000},
    {"name": "Radu-Matei Dragusin", "team": "Spurs", "pos": "DEF", "price": 5000000},
    {"name": "Conor Gallagher", "team": "Spurs", "pos": "MF", "price": 5500000},
    {"name": "Antonin Kinsky", "team": "Spurs", "pos": "GK", "price": 4500000},
    {"name": "Randal Kolo Muani", "team": "Spurs", "pos": "FW", "price": 6000000},
    {"name": "Joao Maria Lobo Alves P Costa Palhinha Goncalves", "team": "Spurs", "pos": "FW", "price": 6000000},
    {"name": "Pedro Antonio Porro Sauceda", "team": "Spurs", "pos": "FW", "price": 6000000},
    {"name": "Cristian Gabriel Romero", "team": "Spurs", "pos": "GK", "price": 5500000},
    {"name": "Pape Matar Sarr", "team": "Spurs", "pos": "FW", "price": 6300000},
    {"name": "Xavi Quentin Shay Simons", "team": "Spurs", "pos": "MF", "price": 5500000},
    {"name": "Dominic Ayodele Solanke-Mitchell", "team": "Spurs", "pos": "MF", "price": 5500000},
    {"name": "Djed Spence Diop", "team": "Spurs", "pos": "DEF", "price": 5000000},
    {"name": "Iyenoma Destiny Udogie", "team": "Spurs", "pos": "DEF", "price": 5000000},
    {"name": "Omar Federico Alderete Fernandez", "team": "Sunderland", "pos": "FW", "price": 6500000},
    {"name": "Abdoullah Mustapha Ba", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Daniel George Ballard", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Brian Ebenezer Adjai Brobbey", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Dennis Cirkin", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Melker Ake Ellborg", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Lutsharel Emiliano Geertruida", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Trai Hume", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Wilson Isidor", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Enzo Jeremy Le Fee", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Reinildo Isnard Mandava", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Simon William Moore", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Nordi Mukiele Mulere", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Romaine Lee Mundle", "team": "Sunderland", "pos": "MF", "price": 5500000},
    {"name": "Luke Terry O'Nien", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Ian Carlo Poveda-Ocampo", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Nilson David Angulo Ramirez", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Adam Lee Richardson", "team": "Sunderland", "pos": "DEF", "price": 5000000},
    {"name": "Robin Gerardus Petrus Roefs", "team": "Sunderland", "pos": "GK", "price": 4500000},
    {"name": "Bertrand Isidore Traore", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Granit Xhaka", "team": "Sunderland", "pos": "FW", "price": 6000000},
    {"name": "Jarrod Bowen", "team": "West Ham", "pos": "MF", "price": 7300000},
    {"name": "Aaron Wan-Bissaka", "team": "West Ham", "pos": "DEF", "price": 4500000},
    {"name": "Alphonse Francis Areola", "team": "West Ham", "pos": "GK", "price": 4500000},
    {"name": "Valentin Mariano Jose Castellanos Gimenez", "team": "West Ham", "pos": "FW", "price": 6000000},
    {"name": "Axel Disasi Mhakinis Belho", "team": "West Ham", "pos": "DEF", "price": 5000000},
    {"name": "Lukasz Marek Fabianski", "team": "West Ham", "pos": "GK", "price": 4200000},
    {"name": "Mads Hermansen", "team": "West Ham", "pos": "GK", "price": 4500000},
    {"name": "Maximilian Kilman", "team": "West Ham", "pos": "DEF", "price": 4500000},
    {"name": "Keiber Alberto Lamadrid Briceno", "team": "West Ham", "pos": "MF", "price": 5500000},
    {"name": "Soungoutou Magassa", "team": "West Ham", "pos": "FW", "price": 6000000},
    {"name": "Konstantinos Mavropanos", "team": "West Ham", "pos": "DEF", "price": 5000000},
    {"name": "Freddie Potts", "team": "West Ham", "pos": "FW", "price": 6000000},
    {"name": "Tomas Soucek", "team": "West Ham", "pos": "MF", "price": 5500000},
    {"name": "Crysencio Jilbert Sylverio Cirro Summerville", "team": "West Ham", "pos": "MF", "price": 6500000},
    {"name": "Jean-Clair Dimitri Roger Todibo", "team": "West Ham", "pos": "DEF", "price": 5000000},
    {"name": "Adama Traore Diarra", "team": "West Ham", "pos": "FW", "price": 6000000},
    {"name": "Kyle Leonardus Walker-Peters", "team": "West Ham", "pos": "FW", "price": 4500000},
    {"name": "Callum Eddie Graham Wilson", "team": "West Ham", "pos": "FW", "price": 6000000},
    {"name": "Badobre Emmanuel Elysee Djedje Agbadou", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Jhon Adolfo Arias Andrade", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Adam James Armstrong", "team": "Wolves", "pos": "FW", "price": 4700000},
    {"name": "Toluwalase Emmanuel Arokodare", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Jeanricner Bellegarde", "team": "Wolves", "pos": "MF", "price": 5500000},
    {"name": "Daniel Ian Bentley", "team": "Wolves", "pos": "GK", "price": 4500000},
    {"name": "Hugo Bueno Lopez", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Matthew James Doherty", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Adilson Angel Abreu Almeida Gomes", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Tote Antonio Gomes", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Joao Victor Gomes Da Silva", "team": "Wolves", "pos": "FW", "price": 6200000},
    {"name": "Harvey Lawson Griffiths", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Hee-Chan Hwang", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Santiago Ignacio Bueno", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Samuel Luke Johnstone", "team": "Wolves", "pos": "GK", "price": 4500000},
    {"name": "Ladislav Krejci", "team": "Wolves", "pos": "FW", "price": 6000000},
    {"name": "Dexter Joeng Woo Lembikisa", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Jose Pedro Malheiro De Sa", "team": "Wolves", "pos": "FW", "price": 4600000},
    {"name": "Rodrigo Martins Gomes", "team": "Wolves", "pos": "MF", "price": 5500000},
    {"name": "Yerson Mosquera Valdelamar", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Jackson Tchatchoua", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Andre Trindade Da Costa Neto", "team": "Wolves", "pos": "FW", "price": 4500000},
    {"name": "David Moller Wolfe", "team": "Wolves", "pos": "DEF", "price": 5000000},
    {"name": "Nathan Benjamin Ake", "team": "Man City", "pos": "DEF", "price": 5500000},
    {"name": "Marcus Bettinelli", "team": "Man City", "pos": "GK", "price": 4000000},
    {"name": "Rayan Mathis Cherki", "team": "Man City", "pos": "MF", "price": 6500000},
    {"name": "Jeremy Baffour Doku", "team": "Man City", "pos": "MF", "price": 8000000},
    {"name": "Gianluigi Donnarumma", "team": "Man City", "pos": "GK", "price": 5000000},
    {"name": "Ruben Dos Santos Gato Alves Dias", "team": "Man City", "pos": "MF", "price": 5000000},
    {"name": "Philip Walter Foden", "team": "Man City", "pos": "MF", "price": 9500000},
    {"name": "Nicolas Gonzalez Iglesias", "team": "Man City", "pos": "MF", "price": 5000000},
    {"name": "Addji Keaninkin Marc-Israel Guehi", "team": "Man City", "pos": "DEF", "price": 5500000},
    {"name": "Josko Gvardiol", "team": "Man City", "pos": "DEF", "price": 7500000},
    {"name": "Erling Braut Haaland", "team": "Man City", "pos": "FW", "price": 15500000},
    {"name": "Rodrigo Hernandez Cascante", "team": "Man City", "pos": "MF", "price": 5000000},
    {"name": "Mateo Kovacic", "team": "Man City", "pos": "MF", "price": 6000000},
    {"name": "Omar Khaled Marmoush", "team": "Man City", "pos": "FW", "price": 8300000},
    {"name": "Bernardo Mota Veiga De Carvalho E Silva", "team": "Man City", "pos": "MF", "price": 5000000},
    {"name": "Matheus Luiz Nunes", "team": "Man City", "pos": "MF", "price": 6000000},
    {"name": "Tijjani Martinus Jan Reijnders", "team": "Man City", "pos": "MF", "price": 7000000},
    {"name": "Antoine Serlom Semenyo", "team": "Man City", "pos": "FW", "price": 5500000},
    {"name": "John Stones", "team": "Man City", "pos": "DEF", "price": 6000000},
    {"name": "James Harrington Trafford", "team": "Man City", "pos": "GK", "price": 4500000},
    {"name": "Rayan Ait-Nouri", "team": "Man City", "pos": "DEF", "price": 5000000},
    {"name": "Altay Bayindir", "team": "Man Utd", "pos": "GK", "price": 4000000},
    {"name": "Bruno Miguel Borges Fernandes", "team": "Man Utd", "pos": "MF", "price": 9000000},
    {"name": "Carlos Henrique Casimiro", "team": "Man Utd", "pos": "MF", "price": 6500000},
    {"name": "Jose Diogo Dalot Teixeira", "team": "Man Utd", "pos": "MF", "price": 5000000},
    {"name": "Matthijs De Ligt", "team": "Man Utd", "pos": "MF", "price": 5000000},
    {"name": "Amad Diallo", "team": "Man Utd", "pos": "MF", "price": 6500000},
    {"name": "Thomas David Heaton", "team": "Man Utd", "pos": "GK", "price": 4000000},
    {"name": "Senne Lammens", "team": "Man Utd", "pos": "GK", "price": 3500000},
    {"name": "Harry Jacob Maguire", "team": "Man Utd", "pos": "DEF", "price": 4500000},
    {"name": "Tyrell Johannes Chicco Malacia", "team": "Man Utd", "pos": "DEF", "price": 4000000},
    {"name": "Lisandro Martinez", "team": "Man Utd", "pos": "DEF", "price": 6500000},
    {"name": "Noussair Mazraoui", "team": "Man Utd", "pos": "DEF", "price": 5500000},
    {"name": "Kobbie Mainoo", "team": "Man Utd", "pos": "MF", "price": 5500000},
    {"name": "Leny Yoro", "team": "Man Utd", "pos": "DEF", "price": 5000000},
    {"name": "Bryan Tetsadong Marceau Mbeumo", "team": "Man Utd", "pos": "FW", "price": 8500000},
    {"name": "Dermot William Mee", "team": "Man Utd", "pos": "MF", "price": 5000000},
    {"name": "Mason Tony Mount", "team": "Man Utd", "pos": "MF", "price": 5500000},
    {"name": "Matheus Santos Carneiro da Cunha", "team": "Man Utd", "pos": "FW", "price": 8000000},
    {"name": "Benjamin Sesko", "team": "Man Utd", "pos": "FW", "price": 7500000},
    {"name": "Luke Paul Hoare Shaw", "team": "Man Utd", "pos": "DEF", "price": 4500000},
    {"name": "Manuel Ugarte Ribeiro", "team": "Man Utd", "pos": "MF", "price": 5000000},
    {"name": "Joshua Orobosa Zirkzee", "team": "Man Utd", "pos": "FW", "price": 7000000},
]


def _stable_id(name: str, pos: str) -> str:
    """Generate a stable ID from name so it never changes when list order changes."""
    import hashlib
    key = (pos + "_" + name).lower().encode()
    return pos.lower() + "_" + hashlib.md5(key).hexdigest()[:8]


_NAME_OVERRIDES = {
    "alexis mac allister": "Alexis Mac Allister",
    "kevin oghenetega tamaraebi bakumo-abraham": "Tammy Abraham",
    "matheus santos carneiro da cunha": "Matheus Cunha",
    "rodrigo hernandez cascante": "Rodri",
    "carlos henrique casimiro": "Casemiro",
    "bruno miguel borges fernandes": "Bruno Fernandes",
    "jose diogo dalot teixeira": "Diogo Dalot",
    "ruben dos santos gato alves dias": "Ruben Dias",
    "gabriel dos santos magalhaes": "Gabriel",
    "gabriel magalhaes": "Gabriel",
    "gabriel teodoro martinelli silva": "Gabriel Martinelli",
    "william saliba": "William Saliba",
    "bernardo mota veiga de carvalho e silva": "Bernardo Silva",
    "rodrigo bentancur": "Rodrigo Bentancur",
    "pedro antonio porro sauceda": "Pedro Porro",
    "joao maria lobo alves p costa palhinha goncalves": "Joao Palhinha",
    "dominic ayodele solanke-mitchell": "Dominic Solanke",
    "cristian gabriel romero": "Cristian Romero",
    "francisco evanilson de lima barbosa": "Evanilson",
    "justin dean kluivert": "Justin Kluivert",
    "marcos nicolas senesi baron": "Nicolas Senesi",
    "marcus joseph tavernier": "Marcus Tavernier",
    "moises isaac caicedo corozo": "Moises Caicedo",
    "joao pedro junqueira de jesus": "Joao Pedro",
    "levi lamar samuels colwill": "Levi Colwill",
    "wesley tidjan fofana": "Wesley Fofana",
    "malo arthur gusto": "Malo Gusto",
    "enzo jeremias fernandez": "Enzo Fernandez",
    "marc cucurella saseta": "Marc Cucurella",
    "joelinton cassio apolinario de lira": "Joelinton",
    "bruno guimaraes rodriguez moura": "Bruno Guimaraes",
    "milos kerkez": "Milos Kerkez",
    "ryan jiro gravenberch": "Ryan Gravenberch",
    "ibrahima konate": "Ibrahima Konate",
    "virgil van dijk": "Virgil Van Dijk",
    "mohamed salah": "Mohamed Salah",
    "andrew robertson": "Andrew Robertson",
    "cody gakpo": "Cody Gakpo",
    "florian richard wirtz": "Florian Wirtz",
    "hugo timothee ekitike": "Hugo Ekitike",
    "jeremie frimpong": "Jeremie Frimpong",
    "damian emiliano martinez romero": "Emi Martinez",
    "oliver george arthur watkins": "Ollie Watkins",
    "morgan elliot rogers": "Morgan Rogers",
    "douglas luiz soares de paulo": "Douglas Luiz",
    "amadou ba z mvom onana": "Amadou Onana",
    "youri marion tielemans": "Youri Tielemans",
    "harvey daniel james elliott": "Harvey Elliott",
    "pau francisco torres": "Pau Torres",
    "emiliano buendia stati": "Emi Buendia",
    "leon patrick bailey": "Leon Bailey",
    "ian ethan maatsen": "Ian Maatsen",
    "philip walter foden": "Phil Foden",
    "rayan mathis cherki": "Rayan Cherki",
    "erling braut haaland": "Erling Haaland",
    "mateo kovacic": "Mateo Kovacic",
    "omar khaled marmoush": "Omar Marmoush",
    "addji keaninkin marc-israel guehi": "Marc Guehi",
    "james harrington trafford": "James Trafford",
    "nicolas gonzalez iglesias": "Nicolas Gonzalez",
    "tijjani martinus jan reijnders": "Tijjani Reijnders",
    "matheus luiz nunes": "Matheus Nunes",
    "antoine serlom semenyo": "Antoine Semenyo",
    "kepa arrizabalaga revuelta": "Kepa",
    "piero martin hincapie reyna": "Piero Hincapie",
    "chukwunonso azuka tristan madueke": "Noni Madueke",
    "mikel merino zazon": "Mikel Merino",
    "david raya martin": "David Raya",
    "martin zubimendi ibanez": "Martin Zubimendi",
    "altay bayindir": "Altay Bayindir",
    "harry jacob maguire": "Harry Maguire",
    "tyrell johannes chicco malacia": "Tyrell Malacia",
    "lisandro martinez": "Lisandro Martinez",
    "noussair mazraoui": "Noussair Mazraoui",
    "bryan tetsadong marceau mbeumo": "Bryan Mbeumo",
    "manuel ugarte ribeiro": "Manuel Ugarte",
    "joshua orobosa zirkzee": "Joshua Zirkzee",
    "josko gvardiol": "Josko Gvardiol",
    "john stones": "John Stones",
    "nathan benjamin ake": "Nathan Ake",
    "rayan ait-nouri": "Rayan Ait-Nouri",
    "gianluigi donnarumma": "Gianluigi Donnarumma",
    "riccardo calafiori": "Riccardo Calafiori",
    "martin odegaard": "Martin Odegaard",
    "declan rice": "Declan Rice",
    "bukayo saka": "Bukayo Saka",
    "jurrien timber": "Jurrien Timber",
    "leandro trossard": "Leandro Trossard",
    "benjamin white": "Ben White",
    "kai havertz": "Kai Havertz",
    "viktor einar gyokeres": "Viktor Gyokeres",
    "eberechi oluchi eze": "Eberechi Eze",
    "gabriel fernando de jesus": "Gabriel Jesus",
    "christian norgaard": "Christian Norgaard",
    "alisson ramses becker": "Alisson",
    "conor bradley": "Conor Bradley",
    "wataru endo": "Wataru Endo",
    "curtis jones": "Curtis Jones",
    "giorgi mamardashvili": "Giorgi Mamardashvili",
    "dominik szoboszlai": "Dominik Szoboszlai",
    "federico chiesa": "Federico Chiesa",
    "alexander isak": "Alexander Isak",
    "idrissa gana gueye": "Idrissa Gueye",
    "jordan lee pickford": "Jordan Pickford",
    "james alan tarkowski": "James Tarkowski",
    "jarrad paul branthwaite": "Jarrad Branthwaite",
    "vitalii mykolenko": "Vitalii Mykolenko",
    "dwight james matthew mcneil": "Dwight McNeil",
    "iliman-cheikh baroy ndiaye": "Iliman Ndiaye",
    "granit xhaka": "Granit Xhaka",
    "joachim christian andersen": "Joachim Andersen",
    "alexander chuka iwobi": "Alex Iwobi",
    "raul alonso jimenez rodriguez": "Raul Jimenez",
    "rodrigo muniz carvalho": "Rodrigo Muniz",
    "antonee robinson": "Antonee Robinson",
    "emile smith rowe": "Emile Smith Rowe",
    "sander gard bolin berge": "Sander Berge",
    "jean-philippe mateta": "Jean-Philippe Mateta",
    "maxence guy lacroix": "Maxence Lacroix",
    "jorgen strand larsen": "Jorgen Strand Larsen",
    "brennan price johnson": "Brennan Johnson",
    "cheick oumar doucoure": "Cheick Doucoure",
    "daniel munoz mejia": "Daniel Munoz",
    "edward keddar nketiah": "Eddie Nketiah",
    "yeremy jesus pino santos": "Yeremy Pino",
    "tyrick mitchell": "Tyrick Mitchell",
    "sandro tonali": "Sandro Tonali",
    "kieran john trippier": "Kieran Trippier",
    "anthony michael gordon": "Anthony Gordon",
    "fabian lukas schar": "Fabian Schar",
    "valentine livramento": "Valentino Livramento",
    "daniel johnson burn": "Dan Burn",
    "harvey lewis barnes": "Harvey Barnes",
    "aaron ramsdale": "Aaron Ramsdale",
    "nicholas david pope": "Nick Pope",
    "morgan anthony gibbs-white": "Morgan Gibbs-White",
    "callum james hudson-odoi": "Callum Hudson-Odoi",
    "neco shay williams": "Neco Williams",
    "christopher grant wood": "Chris Wood",
    "taiwo micheal awoniyi": "Taiwo Awoniyi",
    "ibrahim sangare": "Ibrahim Sangare",
    "matz willy els sels": "Matz Sels",
    "jarrod bowen": "Jarrod Bowen",
    "maximilian kilman": "Max Kilman",
    "tomas soucek": "Tomas Soucek",
    "aaron wan-bissaka": "Aaron Wan-Bissaka",
    "crysencio jilbert sylverio cirro summerville": "Crysencio Summerville",
    "kyle leonardus walker-peters": "Kyle Walker-Peters",
    "conor gallagher": "Conor Gallagher",
    "dejan kulusevski": "Dejan Kulusevski",
    "james maddison": "James Maddison",
    "guglielmo vicario": "Guglielmo Vicario",
    "micky van de ven": "Micky Van De Ven",
    "iyenoma destiny udogie": "Destiny Udogie",
    "richarlison de andrade": "Richarlison",
    "mohammed kudus": "Mohammed Kudus",
    "yves bissouma": "Yves Bissouma",
    "pape matar sarr": "Pape Sarr",
    "xavi quentin shay simons": "Xavi Simons",
    "randal kolo muani": "Randal Kolo Muani",
    "dominic calvert-lewin": "Dominic Calvert-Lewin",
    "pascal augustus struijk": "Pascal Struijk",
    "illan stephane meslier": "Illan Meslier",
    "degnand wilfried gnonto": "Wilfried Gnonto",
    "ethan kwame colm raymond ampadu": "Ethan Ampadu",
    "daniel owen james": "Dan James",
    "hee-chan hwang": "Hwang Hee-chan",
    "andre trindade da costa neto": "Andre",
    "joao victor gomes da silva": "Joao Gomes",
    "rodrigo martins gomes": "Rodrigo Gomes",
    "jose pedro malheiro de sa": "Jose Sa",
    "adilson angel abreu almeida gomes": "Adilson Gomes",
    "pelenda joshua tunga dasilva": "Josh Dasilva",
    "fabio leandro freitas gouveia de carvalho": "Fabio Carvalho",
    "dango aboubacar faissal ouattara": "Dango Ouattara",
    "igor thiago nascimento rodrigues": "Igor Thiago",
    "mikkel krogh damsgaard": "Mikkel Damsgaard",
    "caoimhin odhran kelleher": "Caoimhin Kelleher",
    "sepp van den berg": "Sepp Van Den Berg",
    "carlos jonas alcaraz duran": "Carlos Alcaraz",
    "kiernan frank dewsbury-hall": "Kiernan Dewsbury-Hall",
    "norberto bercique gomes betuncal": "Nuno Tavares",
    "timothy emeka iroegbunam": "Tim Iroegbunam",
    "murillo santiago costa dos santos": "Murillo",
    "felipe rodrigues da silva": "Felipe",
    "nicolo savona": "Nicolo Savona",
    "nicolas martin dominguez": "Nicolas Dominguez",
    "temitayo olufisayo olaoluwa aina": "Timi Aina",
    "lutsharel emiliano geertruida": "Lutsharel Geertruida",
    "enzo jeremy le fee": "Enzo Le Fee",
    "reinildo isnard mandava": "Reinildo",
    "brian ebenezer adjai brobbey": "Brian Brobbey",
    "wilson isidor": "Wilson Isidor",
    "adam lee richardson": "Adam Richardson",
    "bertrand isidore traore": "Bertrand Traore",
    "valentin mariano jose castellanos gimenez": "Taty Castellanos",
    "jean-clair dimitri roger todibo": "Jean-Clair Todibo",
    "axel disasi mhakinis belho": "Axel Disasi",
    "adama traore diarra": "Adama Traore",
    "mads hermansen": "Mads Hermansen",
    "konstantinos mavropanos": "Kostas Mavropanos",
    "james michael edward ward-prowse": "James Ward-Prowse",
    "mohamed zeki amdouni": "Zeki Amdouni",
    "jacob bruun larsen": "Jacob Larsen",
    "joshua ishaele jacob-heron laurent": "Josh Laurent",
    "loum tchaouna": "Loum Tchaouna",
    "mike tresor ndayishimiye": "Mike Tresor",
    "quilindschy hartman": "Quilindschy Hartman",
    "lucas pires silva": "Lucas Pires",
    "lyle brent foster": "Lyle Foster",
    "jhon adolfo arias andrade": "Jhon Duran",
    "toluwalase emmanuel arokodare": "Tolu Arokodare",
    "jeanricner bellegarde": "Jeanricner Bellegarde",
    "hugo bueno lopez": "Hugo Bueno",
    "santiago ignacio bueno": "Santiago Bueno",
    "yerson mosquera valdelamar": "Yerson Mosquera",
    "jackson tchatchoua": "Jackson Tchatchoua",
    "dexter joeng woo lembikisa": "Dexter Lembikisa",
    "david moller wolfe": "David Wolfe",
    "badobre emmanuel elysee djedje agbadou": "Emmanuel Agbadou",
    "matthew james doherty": "Matt Doherty",
    "harvey lawson griffiths": "Harvey Griffiths",
    "ladislav krejci": "Ladislav Krejci",
}

def _build_lookup(raw_list: list) -> tuple[dict, dict, dict]:
    """Build ALL_PLAYERS dict, name→player map, norm_name→player map."""
    all_players = {}
    name_map    = {}
    norm_map    = {}

    for i, p in enumerate(raw_list):
        pid = _stable_id(p["name"], p["pos"])
        # Use well-known name from overrides, else first + last
        _nk = _norm(p["name"])
        if _nk in _NAME_OVERRIDES:
            short_name = _NAME_OVERRIDES[_nk]
        else:
            parts = p["name"].split()
            short_name = parts[0] + " " + parts[-1] if len(parts) > 1 else p["name"]
        entry = {
            "id":       pid,
            "name":     short_name,
            "full_name": p["name"],
            "team":     p["team"],
            "position": p["pos"],
            "price":    p["price"],
        }
        all_players[pid] = entry

        # Name lookups
        nl = p["name"].lower()
        nn = _norm(p["name"])
        name_map[nl] = entry
        norm_map[nn] = entry

        # Also last name
        parts = nl.split()
        if parts:
            last = parts[-1]
            if last not in name_map:
                name_map[last] = entry
            nn_last = _norm(last)
            if nn_last not in norm_map:
                norm_map[nn_last] = entry

    return all_players, name_map, norm_map


# Build both lookups
_UCL_ALL, _UCL_NAME, _UCL_NORM = _build_lookup(UCL_PLAYERS_RAW)
_PL_ALL,  _PL_NAME,  _PL_NORM  = _build_lookup(PL_PLAYERS_RAW)

# Active tournament (set at runtime by sheets.get_setting)
_active = "ucl"


def set_active_tournament(t: str):
    global _active
    _active = t.lower()


def get_all_players() -> dict:
    return _UCL_ALL if _active == "ucl" else _PL_ALL


def get_player(pid: str) -> Optional[dict]:
    """Get player by ID. Falls back to name search for old index-based IDs."""
    players = get_all_players()
    if pid in players:
        return players[pid]
    # Fallback: old IDs were like "mf_047" — try to match by searching full_name
    # This handles squads saved before stable IDs were introduced
    return None


def get_players_by_position(pos: str) -> list:
    return [p for p in get_all_players().values() if p["position"] == pos.upper()]


def find_player_by_name(name: str) -> Optional[dict]:
    """Find player by name — handles accents, full API names, and partial matches."""
    if not name:
        return None
    name_map = _UCL_NAME if _active == "ucl" else _PL_NAME
    norm_map = _UCL_NORM if _active == "ucl" else _PL_NORM

    nl = name.lower().strip()
    nn = _norm(name)
    parts = nn.split()

    # 0. Check name overrides first (e.g. "Gabriel Magalhaes" -> "Gabriel")
    if nn in _NAME_OVERRIDES:
        override_name = _NAME_OVERRIDES[nn].lower()
        if override_name in name_map: return name_map[override_name]

    # 1. Direct full name match
    if nl in name_map: return name_map[nl]
    if nn in norm_map: return norm_map[nn]

    # 1b. Match against display names (from _NAME_OVERRIDES values)
    #     e.g. API sends "Casemiro" which is the display name
    all_players = _PL_ALL if _active == "pl" else _UCL_ALL
    for pid, p in all_players.items():
        display = _norm(p["name"])
        if display == nn:
            return p

    # 2. Try first + last only (skip middle names)
    if len(parts) >= 2:
        first_last = parts[0] + " " + parts[-1]
        if first_last in norm_map: return norm_map[first_last]

    # 3. Try last name only (strong match — must be unique enough, len > 3)
    if len(parts) >= 1:
        last = parts[-1]
        if len(last) > 3 and last in norm_map:
            return norm_map[last]

    # 4. Try reversed 2-word: "Fernandes Bruno"
    if len(parts) == 2:
        rev = parts[1] + " " + parts[0]
        if rev in norm_map: return norm_map[rev]

    # 5. Match if our player's full raw name contains ALL parts of the API name
    for key, p in norm_map.items():
        key_parts = key.split()
        if all(pt in key_parts for pt in parts if len(pt) > 2):
            return p

    # 6. Last name substring match (only if last name is long enough to be unique)
    if len(parts) >= 1:
        last = parts[-1]
        if len(last) >= 5:
            for key, p in norm_map.items():
                if last in key.split():
                    return p

    return None


def fmt_price(price: int) -> str:
    return f"€{price / 1_000_000:.1f}m"


def mask_username(username: str) -> str:
    """Show first and last char, mask middle: 'player' → 'p****r'"""
    if len(username) <= 2:
        return username[0] + "*"
    return username[0] + "*" * (len(username) - 2) + username[-1]
