"""
players.py — Player lists for UCL and PL tournaments.
Switch via active tournament setting.
Prices stored in cents (€5.5m = 5500000) for precision.
"""
import unicodedata
from typing import Optional


def _norm(s: str) -> str:
    """Normalize accents: Dembélé→Dembele, Ødegaard→Odegaard etc."""
    return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower().strip()


# ── UCL Players (Arsenal, PSG, Atletico Madrid, Bayern Munich) ────────────────

UCL_PLAYERS_RAW = [
    # Arsenal
    {"name": "Bukayo Saka",         "team": "Arsenal",  "pos": "MF", "price": 9500000},
    {"name": "Viktor Gyokeres",     "team": "Arsenal",  "pos": "FW", "price": 9000000},
    {"name": "Martin Odegaard",     "team": "Arsenal",  "pos": "MF", "price": 8500000},
    {"name": "Gabriel Martinelli",  "team": "Arsenal",  "pos": "MF", "price": 7500000},
    {"name": "Kai Havertz",         "team": "Arsenal",  "pos": "FW", "price": 7500000},
    {"name": "Eberechi Eze",        "team": "Arsenal",  "pos": "MF", "price": 7500000},
    {"name": "Leandro Trossard",    "team": "Arsenal",  "pos": "MF", "price": 7000000},
    {"name": "Declan Rice",         "team": "Arsenal",  "pos": "MF", "price": 7000000},
    {"name": "Mikel Merino",        "team": "Arsenal",  "pos": "MF", "price": 6500000},
    {"name": "Noni Madueke",        "team": "Arsenal",  "pos": "MF", "price": 6500000},
    {"name": "William Saliba",      "team": "Arsenal",  "pos": "DEF","price": 6000000},
    {"name": "Martin Zubimendi",    "team": "Arsenal",  "pos": "MF", "price": 6000000},
    {"name": "Ethan Nwaneri",       "team": "Arsenal",  "pos": "MF", "price": 5500000},
    {"name": "Max Dowman",          "team": "Arsenal",  "pos": "MF", "price": 5500000},
    {"name": "Gabriel",             "team": "Arsenal",  "pos": "DEF","price": 5500000},
    {"name": "David Raya",          "team": "Arsenal",  "pos": "GK", "price": 5500000},
    {"name": "Ben White",           "team": "Arsenal",  "pos": "DEF","price": 5000000},
    {"name": "Christian Norgaard",  "team": "Arsenal",  "pos": "MF", "price": 5000000},
    {"name": "Piero Hincapie",      "team": "Arsenal",  "pos": "DEF","price": 5000000},
    {"name": "Jurrien Timber",      "team": "Arsenal",  "pos": "DEF","price": 5000000},
    {"name": "Kepa Arrizabalaga",   "team": "Arsenal",  "pos": "GK", "price": 4500000},
    {"name": "Cristhian Mosquera",  "team": "Arsenal",  "pos": "DEF","price": 4500000},
    {"name": "Riccardo Calafiori",  "team": "Arsenal",  "pos": "DEF","price": 4500000},
    {"name": "Myles Lewis-Skelly",  "team": "Arsenal",  "pos": "DEF","price": 4500000},
    {"name": "Tommy Setford",       "team": "Arsenal",  "pos": "GK", "price": 4000000},
    # PSG
    {"name": "Ousmane Dembele",     "team": "PSG",      "pos": "FW", "price": 10000000},
    {"name": "Desire Doue",         "team": "PSG",      "pos": "MF", "price": 8000000},
    {"name": "Khvicha Kvaratskhelia","team": "PSG",     "pos": "MF", "price": 8000000},
    {"name": "Bradley Barcola",     "team": "PSG",      "pos": "MF", "price": 7500000},
    {"name": "Goncalo Ramos",       "team": "PSG",      "pos": "FW", "price": 7000000},
    {"name": "Vitinha",             "team": "PSG",      "pos": "MF", "price": 7000000},
    {"name": "Fabian Ruiz",         "team": "PSG",      "pos": "MF", "price": 6500000},
    {"name": "Nuno Mendes",         "team": "PSG",      "pos": "DEF","price": 6000000},
    {"name": "Achraf Hakimi",       "team": "PSG",      "pos": "DEF","price": 6000000},
    {"name": "Joao Neves",          "team": "PSG",      "pos": "MF", "price": 6000000},
    {"name": "Kang-in Lee",         "team": "PSG",      "pos": "MF", "price": 6000000},
    {"name": "Warren Zaire-Emery",  "team": "PSG",      "pos": "MF", "price": 5500000},
    {"name": "Marquinhos",          "team": "PSG",      "pos": "DEF","price": 5000000},
    {"name": "Willian Pacho",       "team": "PSG",      "pos": "DEF","price": 5000000},
    {"name": "Ibrahim Mbaye",       "team": "PSG",      "pos": "MF", "price": 5000000},
    {"name": "Matvei Safonov",      "team": "PSG",      "pos": "GK", "price": 4500000},
    {"name": "Lucas Chevalier",     "team": "PSG",      "pos": "GK", "price": 4500000},
    {"name": "Senny Mayulu",        "team": "PSG",      "pos": "MF", "price": 4500000},
    {"name": "David Boly",          "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Lucas Hernandez",     "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Lucas Beraldo",       "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Illia Zabarnyi",      "team": "PSG",      "pos": "DEF","price": 4000000},
    {"name": "Martin James",        "team": "PSG",      "pos": "MF", "price": 4000000},
    {"name": "Noham Kamara",        "team": "PSG",      "pos": "DEF","price": 4000000},
    # Atletico Madrid
    {"name": "Julian Alvarez",      "team": "Atletico", "pos": "FW", "price": 9000000},
    {"name": "Antoine Griezmann",   "team": "Atletico", "pos": "FW", "price": 8500000},
    {"name": "Alexander Sorloth",   "team": "Atletico", "pos": "FW", "price": 7500000},
    {"name": "Marcos Llorente",     "team": "Atletico", "pos": "MF", "price": 6500000},
    {"name": "Giuliano Simeone",    "team": "Atletico", "pos": "MF", "price": 6000000},
    {"name": "Giacomo Raspadori",   "team": "Atletico", "pos": "FW", "price": 6000000},
    {"name": "Jan Oblak",           "team": "Atletico", "pos": "GK", "price": 6000000},
    {"name": "Koke",                "team": "Atletico", "pos": "MF", "price": 6000000},
    {"name": "Pablo Barrios",       "team": "Atletico", "pos": "MF", "price": 5500000},
    {"name": "Conor Gallagher",     "team": "Atletico", "pos": "MF", "price": 5500000},
    {"name": "Javier Galan",        "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Carlos Martin",       "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Nicolas Gonzalez",    "team": "Atletico", "pos": "MF", "price": 5000000},
    {"name": "Alex Baena",          "team": "Atletico", "pos": "MF", "price": 5000000},
    {"name": "Thiago Almada",       "team": "Atletico", "pos": "MF", "price": 5000000},
    {"name": "Jose Maria Gimenez",  "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Nahuel Molina",       "team": "Atletico", "pos": "DEF","price": 5000000},
    {"name": "Johnny Cardoso",      "team": "Atletico", "pos": "MF", "price": 4500000},
    {"name": "Juan Musso",          "team": "Atletico", "pos": "GK", "price": 4500000},
    {"name": "Robin Le Normand",    "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "Matteo Ruggeri",      "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "Clement Lenglet",     "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "David Hancko",        "team": "Atletico", "pos": "DEF","price": 4500000},
    {"name": "Mario De Luis",       "team": "Atletico", "pos": "GK", "price": 4000000},
    {"name": "Marc Pubill",         "team": "Atletico", "pos": "DEF","price": 4000000},
    # Bayern Munich
    {"name": "Harry Kane",          "team": "Bayern",   "pos": "FW", "price": 10500000},
    {"name": "Jamal Musiala",       "team": "Bayern",   "pos": "MF", "price": 9000000},
    {"name": "Michael Olise",       "team": "Bayern",   "pos": "MF", "price": 8000000},
    {"name": "Luis Diaz",           "team": "Bayern",   "pos": "FW", "price": 7500000},
    {"name": "Joshua Kimmich",      "team": "Bayern",   "pos": "MF", "price": 6500000},
    {"name": "Serge Gnabry",        "team": "Bayern",   "pos": "MF", "price": 6500000},
    {"name": "Manuel Neuer",        "team": "Bayern",   "pos": "GK", "price": 6000000},
    {"name": "Leon Goretzka",       "team": "Bayern",   "pos": "MF", "price": 5500000},
    {"name": "Konrad Laimer",       "team": "Bayern",   "pos": "MF", "price": 5500000},
    {"name": "Tom Bischof",         "team": "Bayern",   "pos": "MF", "price": 5500000},
    {"name": "Jonathan Tah",        "team": "Bayern",   "pos": "DEF","price": 5500000},
    {"name": "Alphonso Davies",     "team": "Bayern",   "pos": "DEF","price": 5500000},
    {"name": "Dayot Upamecano",     "team": "Bayern",   "pos": "DEF","price": 5000000},
    {"name": "Aleksandar Pavlovic", "team": "Bayern",   "pos": "MF", "price": 5000000},
    {"name": "Raphael Guerreiro",   "team": "Bayern",   "pos": "DEF","price": 5000000},
    {"name": "Minjae Kim",          "team": "Bayern",   "pos": "DEF","price": 5000000},
    {"name": "Josip Stanisic",      "team": "Bayern",   "pos": "DEF","price": 4500000},
    {"name": "Jonas Urbig",         "team": "Bayern",   "pos": "GK", "price": 4500000},
    {"name": "Sacha Boey",          "team": "Bayern",   "pos": "DEF","price": 4000000},
    {"name": "Sven Ulreich",        "team": "Bayern",   "pos": "GK", "price": 4000000},
    {"name": "Hiroki Ito",          "team": "Bayern",   "pos": "DEF","price": 4000000},
]

# ── PL Players (all 20 teams) ──────────────────────────────────────────────────

PL_PLAYERS_RAW = [
    {"name": "Riccardo Calafiori", "team": "Arsenal", "pos": "DEF", "price": 5600000},
    {"name": "Kai Havertz", "team": "Arsenal", "pos": "FW", "price": 7300000},
    {"name": "Christian Norgaard", "team": "Arsenal", "pos": "MF", "price": 5100000},
    {"name": "Martin Odegaard", "team": "Arsenal", "pos": "MF", "price": 7800000},
    {"name": "Declan Rice", "team": "Arsenal", "pos": "MF", "price": 7200000},
    {"name": "Bukayo Saka", "team": "Arsenal", "pos": "MF", "price": 9800000},
    {"name": "William Saliba", "team": "Arsenal", "pos": "DEF", "price": 6100000},
    {"name": "Jurrien Timber", "team": "Arsenal", "pos": "DEF", "price": 6200000},
    {"name": "Leandro Trossard", "team": "Arsenal", "pos": "MF", "price": 6500000},
    {"name": "Kepa Arrizabalaga Revuelta", "team": "Arsenal", "pos": "GK", "price": 45},
    {"name": "Gabriel Dos Santos Magalhães", "team": "Arsenal", "pos": "FW", "price": 60},
    {"name": "Eberechi Oluchi Eze", "team": "Arsenal", "pos": "FW", "price": 7200000},
    {"name": "Gabriel Fernando De Jesus", "team": "Arsenal", "pos": "FW", "price": 6400000},
    {"name": "Viktor Einar Gyökeres", "team": "Arsenal", "pos": "FW", "price": 8800000},
    {"name": "Piero Martin Hincapie Reyna", "team": "Arsenal", "pos": "DEF", "price": 50},
    {"name": "Chukwunonso Azuka Tristan Madueke", "team": "Arsenal", "pos": "FW", "price": 6800000},
    {"name": "Mikel Merino Zazon", "team": "Arsenal", "pos": "MF", "price": 55},
    {"name": "David Raya Martin", "team": "Arsenal", "pos": "GK", "price": 45},
    {"name": "Gabriel Teodoro Martinelli Silva", "team": "Arsenal", "pos": "FW", "price": 6200000},
    {"name": "Benjamin White", "team": "Arsenal", "pos": "FW", "price": 5100000},
    {"name": "Martin Zubimendi Ibanez", "team": "Arsenal", "pos": "FW", "price": 60},
    {"name": "Marco Bizot", "team": "Aston Villa", "pos": "GK", "price": 4200000},
    {"name": "Lucas Digne", "team": "Aston Villa", "pos": "DEF", "price": 4500000},
    {"name": "John McGinn", "team": "Aston Villa", "pos": "MF", "price": 5300000},
    {"name": "Leon Patrick Bailey", "team": "Aston Villa", "pos": "FW", "price": 5500000},
    {"name": "Kevin Oghenetega Tamaraebi Bakumo-Abraham", "team": "Aston Villa", "pos": "FW", "price": 60},
    {"name": "Ross Barkley", "team": "Aston Villa", "pos": "MF", "price": 55},
    {"name": "Emiliano Buendia Stati", "team": "Aston Villa", "pos": "MF", "price": 55},
    {"name": "Matthew Stuart Cash", "team": "Aston Villa", "pos": "DEF", "price": 4700000},
    {"name": "Harvey Daniel James Elliott", "team": "Aston Villa", "pos": "FW", "price": 5100000},
    {"name": "Pau Francisco Torres", "team": "Aston Villa", "pos": "FW", "price": 4300000},
    {"name": "Andres Garcia Robledo", "team": "Aston Villa", "pos": "FW", "price": 60},
    {"name": "Boubacar Bernard Kamara", "team": "Aston Villa", "pos": "MF", "price": 55},
    {"name": "Ezri Ngoyo Konsa", "team": "Aston Villa", "pos": "DEF", "price": 4400000},
    {"name": "Ian Ethan Maatsen", "team": "Aston Villa", "pos": "DEF", "price": 4200000},
    {"name": "Damian Emiliano Martinez Romero", "team": "Aston Villa", "pos": "GK", "price": 5500000},
    {"name": "Tyrone Deon Mings", "team": "Aston Villa", "pos": "DEF", "price": 50},
    {"name": "Amadou Ba Z Mvom Onana", "team": "Aston Villa", "pos": "FW", "price": 4800000},
    {"name": "Victor Jorgen Nilsson Lindelof", "team": "Aston Villa", "pos": "DEF", "price": 50},
    {"name": "Morgan Elliot Rogers", "team": "Aston Villa", "pos": "FW", "price": 7400000},
    {"name": "Jadon Malik Sancho", "team": "Aston Villa", "pos": "MF", "price": 5800000},
    {"name": "Douglas Luiz Soares De Paulo", "team": "Aston Villa", "pos": "FW", "price": 60},
    {"name": "Youri Marion Tielemans", "team": "Aston Villa", "pos": "MF", "price": 5900000},
    {"name": "Oliver George Arthur Watkins", "team": "Aston Villa", "pos": "FW", "price": 8700000},
    {"name": "Ryan Christie", "team": "Bournemouth", "pos": "MF", "price": 4900000},
    {"name": "Enes Unal", "team": "Bournemouth", "pos": "FW", "price": 5400000},
    {"name": "Tyler Shaan Adams", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "Amine Adli", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "Owen Lucas Bevan", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "David Robert Brooks", "team": "Bournemouth", "pos": "MF", "price": 55},
    {"name": "Lewis John Cook", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "Francisco Evanilson De Lima Barbosa", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "William Jonathon Dennis", "team": "Bournemouth", "pos": "MF", "price": 55},
    {"name": "Bafode Diakite", "team": "Bournemouth", "pos": "DEF", "price": 50},
    {"name": "Fraser Gerard Forster", "team": "Bournemouth", "pos": "GK", "price": 45},
    {"name": "James Hill", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "Justin Dean Kluivert", "team": "Bournemouth", "pos": "DEF", "price": 6900000},
    {"name": "Christos Mandas", "team": "Bournemouth", "pos": "GK", "price": 45},
    {"name": "Djorde Petrovic", "team": "Bournemouth", "pos": "GK", "price": 4600000},
    {"name": "Dominic Wadi Sadi", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "Alex Jay Scott", "team": "Bournemouth", "pos": "FW", "price": 5100000},
    {"name": "Marcos Nicolas Senesi Baron", "team": "Bournemouth", "pos": "DEF", "price": 50},
    {"name": "Adam James Smith", "team": "Bournemouth", "pos": "FW", "price": 60},
    {"name": "Marcus Joseph Tavernier", "team": "Bournemouth", "pos": "MF", "price": 5400000},
    {"name": "Adrien Lillan Gaetan Truffert", "team": "Bournemouth", "pos": "FW", "price": 4700000},
    {"name": "Nathan Collins", "team": "Brentford", "pos": "DEF", "price": 4900000},
    {"name": "Vitaly Janelt", "team": "Brentford", "pos": "MF", "price": 4900000},
    {"name": "Kevin Schade", "team": "Brentford", "pos": "MF", "price": 7000000},
    {"name": "Sepp van den Berg", "team": "Brentford", "pos": "DEF", "price": 4600000},
    {"name": "Valentino Mayowa Adedokun", "team": "Brentford", "pos": "MF", "price": 55},
    {"name": "Kristoffer Vassbakk Ajer", "team": "Brentford", "pos": "DEF", "price": 50},
    {"name": "Ellery Ronald Balcombe", "team": "Brentford", "pos": "GK", "price": 45},
    {"name": "Matthew Aidan Cox", "team": "Brentford", "pos": "GK", "price": 45},
    {"name": "Mikkel Krogh Damsgaard", "team": "Brentford", "pos": "MF", "price": 5600000},
    {"name": "Pelenda Joshua Tunga Dasilva", "team": "Brentford", "pos": "DEF", "price": 50},
    {"name": "Fabio Leandro Freitas Gouveia De Carvalho", "team": "Brentford", "pos": "FW", "price": 4600000},
    {"name": "Jordan Brian Henderson", "team": "Brentford", "pos": "FW", "price": 5100000},
    {"name": "Rico Henry", "team": "Brentford", "pos": "FW", "price": 60},
    {"name": "Aaron Buchanan Hickey", "team": "Brentford", "pos": "DEF", "price": 50},
    {"name": "Mathias Jensen", "team": "Brentford", "pos": "FW", "price": 60},
    {"name": "Caoimhin Odhran Kelleher", "team": "Brentford", "pos": "FW", "price": 4800000},
    {"name": "Keane William Lewis-Potter", "team": "Brentford", "pos": "FW", "price": 60},
    {"name": "Igor Thiago Nascimento Rodrigues", "team": "Brentford", "pos": "MF", "price": 55},
    {"name": "Reiss Nelson", "team": "Brentford", "pos": "FW", "price": 60},
    {"name": "Dango Aboubacar Faissal Ouattara", "team": "Brentford", "pos": "FW", "price": 5900000},
    {"name": "Ethan Rupert Pinnock", "team": "Brentford", "pos": "DEF", "price": 50},
    {"name": "Hakon Rafn Valdimarsson", "team": "Brentford", "pos": "GK", "price": 45},
    {"name": "Kaoru Mitoma", "team": "Brighton", "pos": "MF", "price": 6100000},
    {"name": "Georginio Rutter", "team": "Brighton", "pos": "MF", "price": 5600000},
    {"name": "Jan Paul van Hecke", "team": "Brighton", "pos": "DEF", "price": 4600000},
    {"name": "Bart Verbruggen", "team": "Brighton", "pos": "GK", "price": 4500000},
    {"name": "Yasin Ayari", "team": "Brighton", "pos": "MF", "price": 55},
    {"name": "Olivier Boscagli", "team": "Brighton", "pos": "DEF", "price": 50},
    {"name": "Maxim Peter De Cuyper", "team": "Brighton", "pos": "DEF", "price": 50},
    {"name": "Igor Julio Dos Santos De Paulo", "team": "Brighton", "pos": "FW", "price": 60},
    {"name": "Lewis Carl Dunk", "team": "Brighton", "pos": "DEF", "price": 4500000},
    {"name": "Diego Alexander Gomez Amarilla", "team": "Brighton", "pos": "FW", "price": 60},
    {"name": "Pascal Alexander Gross", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Ferdi Erenay Kadioglu", "team": "Brighton", "pos": "MF", "price": 55},
    {"name": "Soloman Benjamin March", "team": "Brighton", "pos": "FW", "price": 60},
    {"name": "Thomas Peter Wayne McGill", "team": "Brighton", "pos": "GK", "price": 45},
    {"name": "James Phillips Milner", "team": "Brighton", "pos": "MF", "price": 55},
    {"name": "Matthew Sean O'Riley", "team": "Brighton", "pos": "MF", "price": 5500000},
    {"name": "Carl Andrew Rushworth", "team": "Brighton", "pos": "GK", "price": 45},
    {"name": "Jason Sean Steele", "team": "Brighton", "pos": "GK", "price": 4200000},
    {"name": "Joel Ivo Veltman", "team": "Brighton", "pos": "DEF", "price": 50},
    {"name": "Adam Harry Webster", "team": "Brighton", "pos": "DEF", "price": 50},
    {"name": "Daniel Welbeck", "team": "Brighton", "pos": "FW", "price": 6300000},
    {"name": "Mats Henrik Berne Wieffer", "team": "Brighton", "pos": "MF", "price": 55},
    {"name": "Armando Broja", "team": "Burnley", "pos": "FW", "price": 5200000},
    {"name": "Maxime Esteve", "team": "Burnley", "pos": "DEF", "price": 3900000},
    {"name": "Zian Flemming", "team": "Burnley", "pos": "MF", "price": 5300000},
    {"name": "Mohamed Zeki Amdouni", "team": "Burnley", "pos": "FW", "price": 4800000},
    {"name": "Jaidon Anthony", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Ashley Barnes", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Martin Dubravka", "team": "Burnley", "pos": "GK", "price": 45},
    {"name": "Marcus Edwards", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Hjalmar Ekdal", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Lyle Brent Foster", "team": "Burnley", "pos": "FW", "price": 4900000},
    {"name": "Quilindschy Hartman", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Vaclav Hladky", "team": "Burnley", "pos": "GK", "price": 45},
    {"name": "Bashir Humphreys", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Jacob Bruun Larsen", "team": "Burnley", "pos": "FW", "price": 5900000},
    {"name": "Joshua Ishaele Jacob-Heron Laurent", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Hannibal Mejbri", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Florentina Ibrain Morris Luis", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Lucas Pires Silva", "team": "Burnley", "pos": "MF", "price": 6200000},
    {"name": "Connor Roberts", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Loum Tchaouna", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Mike Tresor Ndayishimiye", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Axel Tuanzebe", "team": "Burnley", "pos": "FW", "price": 60},
    {"name": "Kyle Andrew Walker", "team": "Burnley", "pos": "FW", "price": 4400000},
    {"name": "James Michael Edward Ward-Prowse", "team": "Burnley", "pos": "MF", "price": 5600000},
    {"name": "Joseph Adrian Worrall", "team": "Burnley", "pos": "MF", "price": 55},
    {"name": "Reece James", "team": "Chelsea", "pos": "DEF", "price": 5600000},
    {"name": "Filip Jorgensen", "team": "Chelsea", "pos": "GK", "price": 4300000},
    {"name": "Cole Palmer", "team": "Chelsea", "pos": "MF", "price": 10500000},
    {"name": "Abdul-Nasir Oluwatosin Adarabioyo", "team": "Chelsea", "pos": "DEF", "price": 50},
    {"name": "Benoit Ntambue Badiashile Mukinayi", "team": "Chelsea", "pos": "DEF", "price": 50},
    {"name": "Moises Isaac Caicedo Corozo", "team": "Chelsea", "pos": "MF", "price": 55},
    {"name": "Trevoh Tom Chalobah", "team": "Chelsea", "pos": "DEF", "price": 50},
    {"name": "Marc Cucurella Saseta", "team": "Chelsea", "pos": "DEF", "price": 50},
    {"name": "Liam Rory Delap", "team": "Chelsea", "pos": "FW", "price": 6200000},
    {"name": "Enzo Jeremias Fernandez", "team": "Chelsea", "pos": "FW", "price": 6500000},
    {"name": "Wesley Tidjan Fofana", "team": "Chelsea", "pos": "DEF", "price": 50},
    {"name": "Malo Arthur Gusto", "team": "Chelsea", "pos": "DEF", "price": 4900000},
    {"name": "Joao Pedro Junqueira De Jesus", "team": "Chelsea", "pos": "FW", "price": 6400000},
    {"name": "Pedro Lomba Neto", "team": "Chelsea", "pos": "FW", "price": 4500000},
    {"name": "Robert Lynch Sanchez", "team": "Chelsea", "pos": "FW", "price": 4800000},
    {"name": "Levi Lamar Samuels Colwill", "team": "Chelsea", "pos": "DEF", "price": 4700000},
    {"name": "Teddy Samuel Sharman-Lowe", "team": "Chelsea", "pos": "GK", "price": 45},
    {"name": "Jorgen Strand Larsen", "team": "Crystal Palace", "pos": "FW", "price": 5900000},
    {"name": "Jean-Philippe Mateta", "team": "Crystal Palace", "pos": "FW", "price": 7600000},
    {"name": "Tyrick Mitchell", "team": "Crystal Palace", "pos": "DEF", "price": 5000000},
    {"name": "Ismaila Sarr", "team": "Crystal Palace", "pos": "MF", "price": 6300000},
    {"name": "Walter Daniel Benitez", "team": "Crystal Palace", "pos": "GK", "price": 45},
    {"name": "Nathaniel Edward Clyne", "team": "Crystal Palace", "pos": "DEF", "price": 50},
    {"name": "Justin Devenny", "team": "Crystal Palace", "pos": "DEF", "price": 50},
    {"name": "Cheick Oumar Doucoure", "team": "Crystal Palace", "pos": "MF", "price": 55},
    {"name": "Evann Ludovic Vidjannagni Guessand", "team": "Crystal Palace", "pos": "FW", "price": 6200000},
    {"name": "Dean Bradley Henderson", "team": "Crystal Palace", "pos": "FW", "price": 5100000},
    {"name": "William James Hughes", "team": "Crystal Palace", "pos": "MF", "price": 55},
    {"name": "Brennan Price Johnson", "team": "Crystal Palace", "pos": "MF", "price": 6500000},
    {"name": "Daichi Kamada", "team": "Crystal Palace", "pos": "MF", "price": 55},
    {"name": "Maxence Guy Lacroix", "team": "Crystal Palace", "pos": "DEF", "price": 5100000},
    {"name": "Jefferson Lerma", "team": "Crystal Palace", "pos": "DEF", "price": 50},
    {"name": "Remi Luke Matthews", "team": "Crystal Palace", "pos": "FW", "price": 60},
    {"name": "Daniel Munoz Mejia", "team": "Crystal Palace", "pos": "DEF", "price": 50},
    {"name": "Edward Keddar Nketiah", "team": "Crystal Palace", "pos": "MF", "price": 5400000},
    {"name": "Yeremy Jesus Pino Santos", "team": "Crystal Palace", "pos": "MF", "price": 55},
    {"name": "Chadi Riad Dnanou", "team": "Crystal Palace", "pos": "FW", "price": 60},
    {"name": "Christopher Jeffrey Richards", "team": "Crystal Palace", "pos": "DEF", "price": 50},
    {"name": "Borna Sosa", "team": "Crystal Palace", "pos": "DEF", "price": 50},
    {"name": "Vitalii Mykolenko", "team": "Everton", "pos": "DEF", "price": 4900000},
    {"name": "Carlos Jonas Alcaraz Duran", "team": "Everton", "pos": "MF", "price": 55},
    {"name": "Thierno Mamadou Barry", "team": "Everton", "pos": "FW", "price": 5700000},
    {"name": "Jarrad Paul Branthwaite", "team": "Everton", "pos": "DEF", "price": 5300000},
    {"name": "Seamus Coleman", "team": "Everton", "pos": "DEF", "price": 50},
    {"name": "Kiernan Frank Dewsbury-Hall", "team": "Everton", "pos": "MF", "price": 55},
    {"name": "James David Garner", "team": "Everton", "pos": "MF", "price": 5300000},
    {"name": "Norberto Bercique Gomes Betuncal", "team": "Everton", "pos": "FW", "price": 60},
    {"name": "Jack Peter Grealish", "team": "Everton", "pos": "FW", "price": 6300000},
    {"name": "Idrissa Gana Gueye", "team": "Everton", "pos": "MF", "price": 55},
    {"name": "Timothy Emeka Iroegbunam", "team": "Everton", "pos": "MF", "price": 55},
    {"name": "Michael Vincent Keane", "team": "Everton", "pos": "FW", "price": 60},
    {"name": "Thomas Lloyd King", "team": "Everton", "pos": "FW", "price": 60},
    {"name": "Dwight James Matthew McNeil", "team": "Everton", "pos": "MF", "price": 5500000},
    {"name": "Iliman-Cheikh Baroy Ndiaye", "team": "Everton", "pos": "MF", "price": 6200000},
    {"name": "Jake Patrick O'Brien", "team": "Everton", "pos": "DEF", "price": 4900000},
    {"name": "Nathan Kenneth Patterson", "team": "Everton", "pos": "DEF", "price": 50},
    {"name": "Jordan Lee Pickford", "team": "Everton", "pos": "GK", "price": 5600000},
    {"name": "Merlin Rohl", "team": "Everton", "pos": "MF", "price": 55},
    {"name": "James Alan Tarkowski", "team": "Everton", "pos": "FW", "price": 5700000},
    {"name": "Mark John Travers", "team": "Everton", "pos": "GK", "price": 45},
    {"name": "Reece Belfield Welch", "team": "Everton", "pos": "DEF", "price": 50},
    {"name": "Calvin Bassey", "team": "Fulham", "pos": "DEF", "price": 4400000},
    {"name": "Bernd Leno", "team": "Fulham", "pos": "GK", "price": 4900000},
    {"name": "Antonee Robinson", "team": "Fulham", "pos": "DEF", "price": 4900000},
    {"name": "Emile Smith Rowe", "team": "Fulham", "pos": "MF", "price": 5600000},
    {"name": "Harry Wilson", "team": "Fulham", "pos": "MF", "price": 6000000},
    {"name": "Joachim Christian Andersen", "team": "Fulham", "pos": "MF", "price": 4500000},
    {"name": "Sander Gard Bolin Berge", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Oscar Bobb", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Alexander Paul Borto", "team": "Fulham", "pos": "FW", "price": 60},
    {"name": "Thomas Cairney", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Samuel Chimerenka Chukwueze", "team": "Fulham", "pos": "FW", "price": 5300000},
    {"name": "Jorge Cuenca Barreno", "team": "Fulham", "pos": "DEF", "price": 50},
    {"name": "Issa Laye Lucas Jean Diop", "team": "Fulham", "pos": "FW", "price": 60},
    {"name": "Alexander Chuka Iwobi", "team": "Fulham", "pos": "MF", "price": 6300000},
    {"name": "Raul Alonso Jimenez Rodriguez", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Benjamin Pascal Lecomte", "team": "Fulham", "pos": "FW", "price": 60},
    {"name": "Sasa Lukic", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Rodrigo Muniz Carvalho", "team": "Fulham", "pos": "MF", "price": 4600000},
    {"name": "Harrison James Reed", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Kouassi Ryan Sessegnon", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Kenny Joelle Tete", "team": "Fulham", "pos": "MF", "price": 55},
    {"name": "Dominic Calvert-Lewin", "team": "Leeds", "pos": "FW", "price": 5700000},
    {"name": "Brenden Russell Aaronson", "team": "Leeds", "pos": "MF", "price": 5400000},
    {"name": "Ethan Kwame Colm Raymond Ampadu", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Jaka Bijol", "team": "Leeds", "pos": "DEF", "price": 50},
    {"name": "Jayden Ian Bogle", "team": "Leeds", "pos": "FW", "price": 4400000},
    {"name": "Sebastiaan Bornauw", "team": "Leeds", "pos": "DEF", "price": 50},
    {"name": "Samuel Mark Byram", "team": "Leeds", "pos": "DEF", "price": 50},
    {"name": "Alex Thomas Cairns", "team": "Leeds", "pos": "GK", "price": 45},
    {"name": "Karl Darlow", "team": "Leeds", "pos": "GK", "price": 45},
    {"name": "Degnand Wilfried Gnonto", "team": "Leeds", "pos": "MF", "price": 5100000},
    {"name": "Ilia Gruev", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Gabriel Johan Gudmundsson", "team": "Leeds", "pos": "DEF", "price": 50},
    {"name": "Daniel Owen James", "team": "Leeds", "pos": "FW", "price": 5600000},
    {"name": "James Michael Justin", "team": "Leeds", "pos": "DEF", "price": 50},
    {"name": "Sean David Longstaff", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Illan Stephane Meslier", "team": "Leeds", "pos": "GK", "price": 4100000},
    {"name": "Lukas Okechukwu Nmecha", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Noah Arinzechukwu Okafor", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Lucas Estella Perri", "team": "Leeds", "pos": "GK", "price": 45},
    {"name": "Joel Mohammed Ramzan Piroe", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Joseph Peter Rodon", "team": "Leeds", "pos": "DEF", "price": 50},
    {"name": "Anton Levi Stach", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Pascal Augustus Struijk", "team": "Leeds", "pos": "DEF", "price": 4300000},
    {"name": "Ao Tanaka", "team": "Leeds", "pos": "MF", "price": 55},
    {"name": "Conor Bradley", "team": "Liverpool", "pos": "DEF", "price": 4900000},
    {"name": "Jeremie Frimpong", "team": "Liverpool", "pos": "DEF", "price": 5700000},
    {"name": "Cody Gakpo", "team": "Liverpool", "pos": "MF", "price": 7300000},
    {"name": "Alexander Isak", "team": "Liverpool", "pos": "FW", "price": 10300000},
    {"name": "Ibrahima Konate", "team": "Liverpool", "pos": "DEF", "price": 5500000},
    {"name": "Alexis Mac Allister", "team": "Liverpool", "pos": "MF", "price": 6300000},
    {"name": "Giorgi Mamardashvili", "team": "Liverpool", "pos": "GK", "price": 4100000},
    {"name": "Andrew Robertson", "team": "Liverpool", "pos": "DEF", "price": 5700000},
    {"name": "Mohamed Salah", "team": "Liverpool", "pos": "MF", "price": 14000000},
    {"name": "Dominik Szoboszlai", "team": "Liverpool", "pos": "MF", "price": 7100000},
    {"name": "Virgil van Dijk", "team": "Liverpool", "pos": "DEF", "price": 6200000},
    {"name": "Owen Michael Beck", "team": "Liverpool", "pos": "FW", "price": 60},
    {"name": "Alisson Ramses Becker", "team": "Liverpool", "pos": "GK", "price": 5400000},
    {"name": "Federico Chiesa", "team": "Liverpool", "pos": "FW", "price": 60},
    {"name": "Harvey Davies", "team": "Liverpool", "pos": "GK", "price": 45},
    {"name": "Hugo Timothee Ekitike", "team": "Liverpool", "pos": "FW", "price": 9100000},
    {"name": "Wataru Endo", "team": "Liverpool", "pos": "MF", "price": 55},
    {"name": "Joseph David Gomez", "team": "Liverpool", "pos": "FW", "price": 60},
    {"name": "Ryan Jiro Gravenberch", "team": "Liverpool", "pos": "MF", "price": 5500000},
    {"name": "Curtis Jones", "team": "Liverpool", "pos": "FW", "price": 60},
    {"name": "Milos Kerkez", "team": "Liverpool", "pos": "MF", "price": 55},
    {"name": "Calvin Ramsay", "team": "Liverpool", "pos": "FW", "price": 60},
    {"name": "Rhys Williams", "team": "Liverpool", "pos": "FW", "price": 60},
    {"name": "Florian Richard Wirtz", "team": "Liverpool", "pos": "FW", "price": 8300000},
    {"name": "Frederick John Woodman", "team": "Liverpool", "pos": "GK", "price": 45},
    {"name": "Aaron Ramsdale", "team": "Newcastle", "pos": "GK", "price": 4500000},
    {"name": "Yoane Wissa", "team": "Newcastle", "pos": "FW", "price": 7300000},
    {"name": "Joelinton Cassio Apolinario De Lira", "team": "Newcastle", "pos": "FW", "price": 60},
    {"name": "Harvey Lewis Barnes", "team": "Newcastle", "pos": "FW", "price": 60},
    {"name": "Sven Adriaan Botman", "team": "Newcastle", "pos": "DEF", "price": 50},
    {"name": "Daniel Johnson Burn", "team": "Newcastle", "pos": "DEF", "price": 5000000},
    {"name": "Anthony David Junior Elanga", "team": "Newcastle", "pos": "FW", "price": 6000000},
    {"name": "Mark Joseph Gillespie", "team": "Newcastle", "pos": "GK", "price": 45},
    {"name": "Anthony Michael Gordon", "team": "Newcastle", "pos": "MF", "price": 55},
    {"name": "Bruno Guimaraes Rodriguez Moura", "team": "Newcastle", "pos": "MF", "price": 55},
    {"name": "Emil Henry Kristoffer Kraft", "team": "Newcastle", "pos": "DEF", "price": 50},
    {"name": "Valentino Livramento", "team": "Newcastle", "pos": "DEF", "price": 4900000},
    {"name": "Jacob Kai Murphy", "team": "Newcastle", "pos": "FW", "price": 60},
    {"name": "William Idamudia Daugaard Osula", "team": "Newcastle", "pos": "FW", "price": 60},
    {"name": "Nicholas David Pope", "team": "Newcastle", "pos": "FW", "price": 5000000},
    {"name": "Jacob Matthew Decourcey Ramsey", "team": "Newcastle", "pos": "FW", "price": 5300000},
    {"name": "John Thomas Gordon Ruddy", "team": "Newcastle", "pos": "GK", "price": 45},
    {"name": "Fabian Lukas Schar", "team": "Newcastle", "pos": "DEF", "price": 5200000},
    {"name": "Malick Thiaw", "team": "Newcastle", "pos": "DEF", "price": 50},
    {"name": "Sandro Tonali", "team": "Newcastle", "pos": "MF", "price": 55},
    {"name": "Kieran John Trippier", "team": "Newcastle", "pos": "DEF", "price": 50},
    {"name": "Joseph George Willock", "team": "Newcastle", "pos": "FW", "price": 60},
    {"name": "Nick Woltemade", "team": "Newcastle", "pos": "FW", "price": 60},
    {"name": "Nikola Milenkovic", "team": "Nottm Forest", "pos": "DEF", "price": 4700000},
    {"name": "Temitayo Olufisayo Olaoluwa Aina", "team": "Nottm Forest", "pos": "MF", "price": 4900000},
    {"name": "Elliot Junior Anderson", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "Taiwo Micheal Awoniyi", "team": "Nottm Forest", "pos": "FW", "price": 5800000},
    {"name": "Dilane Ros-Anderson Bakwa", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "Murillo Santiago Costa Dos Santos", "team": "Nottm Forest", "pos": "DEF", "price": 50},
    {"name": "Nicolas Martin Dominguez", "team": "Nottm Forest", "pos": "MF", "price": 55},
    {"name": "Morgan Anthony Gibbs-White", "team": "Nottm Forest", "pos": "MF", "price": 6300000},
    {"name": "Omari Elijah Giraud-Hutchinson", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "Angus Fraser James Gunn", "team": "Nottm Forest", "pos": "GK", "price": 45},
    {"name": "Callum James Hudson-Odoi", "team": "Nottm Forest", "pos": "MF", "price": 55},
    {"name": "Lorenzo Lucca", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "Igor Jesus Maciel Da Cruz", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "John Victor Maciel Furtado", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "James John McAtee", "team": "Nottm Forest", "pos": "MF", "price": 55},
    {"name": "Dan Ndoye", "team": "Nottm Forest", "pos": "MF", "price": 55},
    {"name": "Luca Netz", "team": "Nottm Forest", "pos": "DEF", "price": 50},
    {"name": "Stefan Ortega Moreno", "team": "Nottm Forest", "pos": "GK", "price": 45},
    {"name": "Felipe Rodrigues Da Silva", "team": "Nottm Forest", "pos": "MF", "price": 6200000},
    {"name": "Ibrahim Sangare", "team": "Nottm Forest", "pos": "MF", "price": 55},
    {"name": "Nicolo Savona", "team": "Nottm Forest", "pos": "DEF", "price": 50},
    {"name": "Matz Willy Els Sels", "team": "Nottm Forest", "pos": "GK", "price": 5000000},
    {"name": "Neco Shay Williams", "team": "Nottm Forest", "pos": "FW", "price": 60},
    {"name": "Christopher Grant Wood", "team": "Nottm Forest", "pos": "FW", "price": 6700000},
    {"name": "Ryan James Yates", "team": "Nottm Forest", "pos": "MF", "price": 55},
    {"name": "Mohammed Kudus", "team": "Spurs", "pos": "MF", "price": 6700000},
    {"name": "Dejan Kulusevski", "team": "Spurs", "pos": "MF", "price": 6700000},
    {"name": "James Maddison", "team": "Spurs", "pos": "MF", "price": 6400000},
    {"name": "Micky van de Ven", "team": "Spurs", "pos": "DEF", "price": 5200000},
    {"name": "Guglielmo Vicario", "team": "Spurs", "pos": "GK", "price": 5000000},
    {"name": "Brandon Anthony Austin", "team": "Spurs", "pos": "GK", "price": 45},
    {"name": "Rodrigo Bentancur", "team": "Spurs", "pos": "MF", "price": 55},
    {"name": "Yves Bissouma", "team": "Spurs", "pos": "MF", "price": 55},
    {"name": "Matthew George Craig", "team": "Spurs", "pos": "FW", "price": 60},
    {"name": "Kevin Danso", "team": "Spurs", "pos": "DEF", "price": 50},
    {"name": "Benjamin Thomas Davies", "team": "Spurs", "pos": "GK", "price": 45},
    {"name": "Richarlison De Andrade", "team": "Spurs", "pos": "FW", "price": 60},
    {"name": "Radu-Matei Dragusin", "team": "Spurs", "pos": "DEF", "price": 50},
    {"name": "Conor Gallagher", "team": "Spurs", "pos": "MF", "price": 55},
    {"name": "Antonin Kinsky", "team": "Spurs", "pos": "GK", "price": 45},
    {"name": "Randal Kolo Muani", "team": "Spurs", "pos": "FW", "price": 60},
    {"name": "Joao Maria Lobo Alves P Costa Palhinha Goncalves", "team": "Spurs", "pos": "FW", "price": 60},
    {"name": "Pedro Antonio Porro Sauceda", "team": "Spurs", "pos": "FW", "price": 60},
    {"name": "Cristian Gabriel Romero", "team": "Spurs", "pos": "GK", "price": 5500000},
    {"name": "Pape Matar Sarr", "team": "Spurs", "pos": "FW", "price": 6300000},
    {"name": "Xavi Quentin Shay Simons", "team": "Spurs", "pos": "MF", "price": 55},
    {"name": "Dominic Ayodele Solanke-Mitchell", "team": "Spurs", "pos": "MF", "price": 55},
    {"name": "Djed Spence Diop", "team": "Spurs", "pos": "DEF", "price": 50},
    {"name": "Iyenoma Destiny Udogie", "team": "Spurs", "pos": "DEF", "price": 50},
    {"name": "Omar Federico Alderete Fernandez", "team": "Sunderland", "pos": "FW", "price": 6500000},
    {"name": "Abdoullah Mustapha Ba", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Daniel George Ballard", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Brian Ebenezer Adjai Brobbey", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Dennis Cirkin", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Melker Ake Ellborg", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Lutsharel Emiliano Geertruida", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Trai Hume", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Wilson Isidor", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Enzo Jeremy Le Fee", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Reinildo Isnard Mandava", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Simon William Moore", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Nordi Mukiele Mulere", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Romaine Lee Mundle", "team": "Sunderland", "pos": "MF", "price": 55},
    {"name": "Luke Terry O'Nien", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Ian Carlo Poveda-Ocampo", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Nilson David Angulo Ramirez", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Adam Lee Richardson", "team": "Sunderland", "pos": "DEF", "price": 50},
    {"name": "Robin Gerardus Petrus Roefs", "team": "Sunderland", "pos": "GK", "price": 45},
    {"name": "Bertrand Isidore Traore", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Granit Xhaka", "team": "Sunderland", "pos": "FW", "price": 60},
    {"name": "Jarrod Bowen", "team": "West Ham", "pos": "MF", "price": 7300000},
    {"name": "Aaron Wan-Bissaka", "team": "West Ham", "pos": "DEF", "price": 4500000},
    {"name": "Alphonse Francis Areola", "team": "West Ham", "pos": "GK", "price": 45},
    {"name": "Valentin Mariano Jose Castellanos Gimenez", "team": "West Ham", "pos": "FW", "price": 60},
    {"name": "Axel Disasi Mhakinis Belho", "team": "West Ham", "pos": "DEF", "price": 50},
    {"name": "Lukasz Marek Fabianski", "team": "West Ham", "pos": "GK", "price": 4200000},
    {"name": "Mads Hermansen", "team": "West Ham", "pos": "GK", "price": 45},
    {"name": "Maximilian Kilman", "team": "West Ham", "pos": "DEF", "price": 4500000},
    {"name": "Keiber Alberto Lamadrid Briceno", "team": "West Ham", "pos": "MF", "price": 55},
    {"name": "Soungoutou Magassa", "team": "West Ham", "pos": "FW", "price": 60},
    {"name": "Konstantinos Mavropanos", "team": "West Ham", "pos": "DEF", "price": 50},
    {"name": "Freddie Potts", "team": "West Ham", "pos": "FW", "price": 60},
    {"name": "Tomas Soucek", "team": "West Ham", "pos": "MF", "price": 55},
    {"name": "Crysencio Jilbert Sylverio Cirro Summerville", "team": "West Ham", "pos": "MF", "price": 6500000},
    {"name": "Jean-Clair Dimitri Roger Todibo", "team": "West Ham", "pos": "DEF", "price": 50},
    {"name": "Adama Traore Diarra", "team": "West Ham", "pos": "FW", "price": 60},
    {"name": "Kyle Leonardus Walker-Peters", "team": "West Ham", "pos": "FW", "price": 4500000},
    {"name": "Callum Eddie Graham Wilson", "team": "West Ham", "pos": "FW", "price": 6000000},
    {"name": "Badobre Emmanuel Elysee Djedje Agbadou", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Jhon Adolfo Arias Andrade", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Adam James Armstrong", "team": "Wolves", "pos": "FW", "price": 4700000},
    {"name": "Toluwalase Emmanuel Arokodare", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Jeanricner Bellegarde", "team": "Wolves", "pos": "MF", "price": 55},
    {"name": "Daniel Ian Bentley", "team": "Wolves", "pos": "GK", "price": 45},
    {"name": "Hugo Bueno Lopez", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Matthew James Doherty", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Adilson Angel Abreu Almeida Gomes", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Tote Antonio Gomes", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Joao Victor Gomes Da Silva", "team": "Wolves", "pos": "FW", "price": 6200000},
    {"name": "Harvey Lawson Griffiths", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Hee-Chan Hwang", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Santiago Ignacio Bueno", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Samuel Luke Johnstone", "team": "Wolves", "pos": "GK", "price": 45},
    {"name": "Ladislav Krejci", "team": "Wolves", "pos": "FW", "price": 60},
    {"name": "Dexter Joeng Woo Lembikisa", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Jose Pedro Malheiro De Sa", "team": "Wolves", "pos": "FW", "price": 4600000},
    {"name": "Rodrigo Martins Gomes", "team": "Wolves", "pos": "MF", "price": 55},
    {"name": "Yerson Mosquera Valdelamar", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Jackson Tchatchoua", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Andre Trindade Da Costa Neto", "team": "Wolves", "pos": "FW", "price": 4500000},
    {"name": "David Moller Wolfe", "team": "Wolves", "pos": "DEF", "price": 50},
    {"name": "Nathan Benjamin Ake", "team": "Man City", "pos": "DEF", "price": 55},
    {"name": "Marcus Bettinelli", "team": "Man City", "pos": "GK", "price": 40},
    {"name": "Rayan Mathis Cherki", "team": "Man City", "pos": "MF", "price": 65},
    {"name": "Jeremy Baffour Doku", "team": "Man City", "pos": "MF", "price": 80},
    {"name": "Gianluigi Donnarumma", "team": "Man City", "pos": "GK", "price": 50},
    {"name": "Ruben Dos Santos Gato Alves Dias", "team": "Man City", "pos": "MF", "price": 50},
    {"name": "Philip Walter Foden", "team": "Man City", "pos": "MF", "price": 95},
    {"name": "Nicolas Gonzalez Iglesias", "team": "Man City", "pos": "MF", "price": 50},
    {"name": "Addji Keaninkin Marc-Israel Guehi", "team": "Man City", "pos": "DEF", "price": 55},
    {"name": "Josko Gvardiol", "team": "Man City", "pos": "DEF", "price": 75},
    {"name": "Erling Braut Haaland", "team": "Man City", "pos": "FW", "price": 155},
    {"name": "Rodrigo Hernandez Cascante", "team": "Man City", "pos": "MF", "price": 50},
    {"name": "Mateo Kovacic", "team": "Man City", "pos": "MF", "price": 60},
    {"name": "Omar Khaled Marmoush", "team": "Man City", "pos": "FW", "price": 83},
    {"name": "Bernardo Mota Veiga De Carvalho E Silva", "team": "Man City", "pos": "MF", "price": 50},
    {"name": "Matheus Luiz Nunes", "team": "Man City", "pos": "MF", "price": 60},
    {"name": "Tijjani Martinus Jan Reijnders", "team": "Man City", "pos": "MF", "price": 70},
    {"name": "Antoine Serlom Semenyo", "team": "Man City", "pos": "FW", "price": 55},
    {"name": "John Stones", "team": "Man City", "pos": "DEF", "price": 60},
    {"name": "James Harrington Trafford", "team": "Man City", "pos": "GK", "price": 45},
    {"name": "Rayan Ait-Nouri", "team": "Man City", "pos": "DEF", "price": 50},
    {"name": "Altay Bayindir", "team": "Man Utd", "pos": "GK", "price": 40},
    {"name": "Bruno Miguel Borges Fernandes", "team": "Man Utd", "pos": "MF", "price": 90},
    {"name": "Carlos Henrique Casimiro", "team": "Man Utd", "pos": "MF", "price": 65},
    {"name": "Jose Diogo Dalot Teixeira", "team": "Man Utd", "pos": "MF", "price": 50},
    {"name": "Matthijs De Ligt", "team": "Man Utd", "pos": "MF", "price": 50},
    {"name": "Amad Diallo", "team": "Man Utd", "pos": "MF", "price": 65},
    {"name": "Thomas David Heaton", "team": "Man Utd", "pos": "GK", "price": 40},
    {"name": "Senne Lammens", "team": "Man Utd", "pos": "GK", "price": 35},
    {"name": "Harry Jacob Maguire", "team": "Man Utd", "pos": "DEF", "price": 45},
    {"name": "Tyrell Johannes Chicco Malacia", "team": "Man Utd", "pos": "DEF", "price": 40},
    {"name": "Lisandro Martinez", "team": "Man Utd", "pos": "DEF", "price": 65},
    {"name": "Noussair Mazraoui", "team": "Man Utd", "pos": "DEF", "price": 55},
    {"name": "Bryan Tetsadong Marceau Mbeumo", "team": "Man Utd", "pos": "FW", "price": 85},
    {"name": "Dermot William Mee", "team": "Man Utd", "pos": "MF", "price": 50},
    {"name": "Mason Tony Mount", "team": "Man Utd", "pos": "MF", "price": 55},
    {"name": "Matheus Santos Carneiro da Cunha", "team": "Man Utd", "pos": "FW", "price": 80},
    {"name": "Benjamin Sesko", "team": "Man Utd", "pos": "FW", "price": 75},
    {"name": "Luke Paul Hoare Shaw", "team": "Man Utd", "pos": "DEF", "price": 45},
    {"name": "Manuel Ugarte Ribeiro", "team": "Man Utd", "pos": "MF", "price": 50},
    {"name": "Joshua Orobosa Zirkzee", "team": "Man Utd", "pos": "FW", "price": 70},
]


def _build_lookup(raw_list: list) -> tuple[dict, dict, dict]:
    """Build ALL_PLAYERS dict, name→player map, norm_name→player map."""
    all_players = {}
    name_map    = {}
    norm_map    = {}

    for i, p in enumerate(raw_list):
        pid = f"{p['pos'].lower()}_{i:03d}"
        entry = {
            "id":       pid,
            "name":     p["name"],
            "team":     p["team"],
            "position": p["pos"],
            "price":    p["price"],
        }
        all_players[pid] = entry

        # Name lookups
        nl = p["name"].lower()
        nn = _norm(p["name"])
        name_map[nl] = entry
        norm_map[nn] = entry

        # Also last name
        parts = nl.split()
        if parts:
            last = parts[-1]
            if last not in name_map:
                name_map[last] = entry
            nn_last = _norm(last)
            if nn_last not in norm_map:
                norm_map[nn_last] = entry

    return all_players, name_map, norm_map


# Build both lookups
_UCL_ALL, _UCL_NAME, _UCL_NORM = _build_lookup(UCL_PLAYERS_RAW)
_PL_ALL,  _PL_NAME,  _PL_NORM  = _build_lookup(PL_PLAYERS_RAW)

# Active tournament (set at runtime by sheets.get_setting)
_active = "ucl"


def set_active_tournament(t: str):
    global _active
    _active = t.lower()


def get_all_players() -> dict:
    return _UCL_ALL if _active == "ucl" else _PL_ALL


def get_player(pid: str) -> Optional[dict]:
    return get_all_players().get(pid)


def get_players_by_position(pos: str) -> list:
    return [p for p in get_all_players().values() if p["position"] == pos.upper()]


def find_player_by_name(name: str) -> Optional[dict]:
    """Find player by name — handles accents and surname-first formats."""
    if not name:
        return None
    name_map = _UCL_NAME if _active == "ucl" else _PL_NAME
    norm_map = _UCL_NORM if _active == "ucl" else _PL_NORM

    nl = name.lower().strip()
    nn = _norm(name)

    # Direct match
    if nl in name_map: return name_map[nl]
    if nn in norm_map: return norm_map[nn]

    # Try reversed: "Kane H." → "h. kane"
    parts = nn.split()
    if len(parts) == 2:
        rev = parts[1] + " " + parts[0]
        if rev in norm_map: return norm_map[rev]

    # Partial match on any part > 2 chars
    for part in parts:
        part = part.strip(".")
        if len(part) > 2:
            if part in norm_map: return norm_map[part]
            for key, p in norm_map.items():
                if part in key or key in part:
                    return p
    return None


def fmt_price(price: int) -> str:
    return f"€{price / 1_000_000:.1f}m"


def mask_username(username: str) -> str:
    """Show first and last char, mask middle: 'player' → 'p****r'"""
    if len(username) <= 2:
        return username[0] + "*"
    return username[0] + "*" * (len(username) - 2) + username[-1]
